"use strict";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={avatar:0,found:new Set(),fakes:new Set(),zoom:1,pending:null,quiz:0,joker:true,powerUses:3,hints:0,hintSteps:{},picks:[],chapter:0,level:"main",bonusFound:new Set(),score:0,timed:false,seconds:2400,mapPieces:new Set(),archiveSort:[],chapterPicks:[]};
const avatarPath=i=>`assets/avatars/avatar-${i+1}.png`;
const protocol={started:new Date().toISOString(),events:[]};
function logEvent(type,detail){protocol.events.push({time:new Date().toISOString(),type,detail});saveProtocol()}
function saveProtocol(){const snapshot={started:protocol.started,updated:new Date().toISOString(),avatar:DETECTIVE_DATA.avatars[state.avatar].name,chapter:state.chapter+1,level:state.level,score:state.score,hints:state.hints,timed:state.timed,mainFound:[...state.found].map(i=>DETECTIVE_DATA.spots[i][0]),bonusFound:[...state.bonusFound].map(i=>DETECTIVE_DATA.bonus[i][0]),fakes:[...state.fakes].map(i=>DETECTIVE_DATA.fakes[i][0]),events:protocol.events};localStorage.setItem("kirchendetektiv-protokoll",JSON.stringify(snapshot))}
function protocolText(){const data=JSON.parse(localStorage.getItem("kirchendetektiv-protokoll")||"{}"),list=(title,items)=>`\n## ${title}\n${items?.length?items.map(x=>`- ${x}`).join("\n"):"- noch keine"}\n`;return `# Lernprotokoll: Kirchendetektiv\n\nAutomatisch lokal gespeichert: ${new Date(data.updated||Date.now()).toLocaleString("de-DE")}\nDetektivfigur: ${data.avatar||DETECTIVE_DATA.avatars[state.avatar].name}\nAktueller Abschnitt: ${data.level==="bonus"?"Katholisches Bonuslevel":`Evangelische Kirche, Kapitel ${data.chapter||1}`}\nPunkte: ${data.score||0}\nDetektivrang: ${rank()}\nGenutzte Hinweise: ${data.hints||0}\nZeit-Challenge: ${data.timed?"aktiviert":"nicht aktiviert"}\n${list("Entdeckte Elemente in der evangelischen Kirche",data.mainFound)}${list("Entdeckte Elemente im katholischen Bonuslevel",data.bonusFound)}${list("Erkannte Fehlspuren",data.fakes)}\n## Reflexionsfrage\nWarum bewahren Menschen besondere Zeichen und Orte auf?\n\n## Abschluss\nGemeinsamer Code: ${state.bonusFound.size===6?"F7-KOMET-29":"noch nicht freigeschaltet"}\n`}
function addScore(points){state.score=Math.max(0,state.score+points);$("#scoreCount").textContent=state.score;saveProtocol()}
function startTimer(){if(!state.timed)return;$("#timerChip").classList.remove("hidden");setInterval(()=>{if(state.seconds<1)return;state.seconds--;$("#timerText").textContent=`${String(Math.floor(state.seconds/60)).padStart(2,"0")}:${String(state.seconds%60).padStart(2,"0")}`},1000)}
function downloadProtocol(){saveProtocol();const blob=new Blob([protocolText()],{type:"text/plain;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="kirchendetektiv-lernprotokoll.txt";a.click();setTimeout(()=>URL.revokeObjectURL(url),500);logEvent("Protokoll heruntergeladen","TXT-Datei für Teams erstellt")}
function screen(id){$$(".screen").forEach(x=>x.classList.toggle("active",x.id===id))}
function tap(sel,fn){let t=0;const run=e=>{const x=e.target.closest(sel);if(x)fn(x,e)};document.addEventListener("touchstart",e=>{t=Date.now();run(e)},{passive:true});document.addEventListener("click",e=>{if(Date.now()-t>650)run(e)})}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function renderAvatars(){$("#avatarGrid").innerHTML=DETECTIVE_DATA.avatars.map((a,i)=>`<button class="avatar-card${i===state.avatar?" selected":""}" data-avatar="${i}"><img src="${avatarPath(i)}" alt="${a.name}"><strong>${a.name}: ${a.skill}</strong><small>${a.help}</small></button>`).join("")}
function selectAvatar(i){state.avatar=i;renderAvatars();$("#guideAvatar").src=avatarPath(i);$("#guideAvatar").alt=DETECTIVE_DATA.avatars[i].name;$("#guideName").textContent=`${DETECTIVE_DATA.avatars[i].name} · ${DETECTIVE_DATA.avatars[i].skill}`;saveProtocol()}
function spotHtml(item,i,fake){const done=(fake?state.fakes:state.found).has(i),big=state.avatar===0?" eagle":"",kind=fake?" fake":"";return `<button class="hotspot${kind}${big}${done?" revealed":""}" style="left:${item[1]}%;top:${item[2]}%" data-spot="${i}" data-fake="${fake}" aria-label="${done?item[0]:"Stelle untersuchen"}">${done?(fake?"×":"✓"):""}</button>`}
function renderSpots(){if(state.level==="bonus"){renderBonusSpots();return}const ids=DETECTIVE_DATA.chapters[state.chapter].ids;$("#hotspotLayer").innerHTML=[...ids.map(i=>spotHtml(DETECTIVE_DATA.spots[i],i,false)),...DETECTIVE_DATA.fakes.map((x,i)=>spotHtml(x,i,true))].join("")}
function openDialog(kicker,title,text,body){$("#dialogAvatar").src=avatarPath(state.avatar);$("#dialogKicker").textContent=kicker;$("#dialogTitle").textContent=title;$("#dialogText").textContent=text;$("#dialogTask").innerHTML=body;$("#dialog").showModal()}
function investigate(btn){const i=+btn.dataset.spot,fake=btn.dataset.fake==="true";if(fake){if(!state.fakes.has(i))addScore(-10);state.fakes.add(i);logEvent("Fehlspur erkannt",DETECTIVE_DATA.fakes[i][0]);renderSpots();openDialog("Fehlspur",DETECTIVE_DATA.fakes[i][0],`Pfarrer Falk: „Gute Beobachtung. Aber diese Sache gehört nicht zu den Erinnerungsabzeichen.“`,`<button class="primary" data-action="close-dialog">Weiter suchen</button>`);return}if(state.found.has(i)){openChest();return}state.pending=i;const s=DETECTIVE_DATA.spots[i];openDialog("Echte Spur entdeckt",s[0],`${DETECTIVE_DATA.avatars[state.avatar].name}: „${s[4]}“ Pfarrer Falk: „Löst nun die Ermittlungsaufgabe. Dann wandert das Abzeichen in eure Truhe.“`,`<button class="primary" data-action="open-mini">Aufgabe öffnen</button>`)}
function startMini(){const s=DETECTIVE_DATA.spots[state.pending];$("#dialog").close();$("#gameTitle").textContent=s[0];$("#gameIntro").textContent=s[7];$("#gameBody").innerHTML=miniHtml(s);$("#gameDialog").showModal()}
function miniHtml(s){const type=s[6],items=shuffle(s[8]);if(type==="letters")return `<div class="letter-build"><div class="build-target" id="buildTarget"></div><div class="tile-row">${shuffle([...s[8]]).map(x=>`<button data-tile="${x}">${x}</button>`).join("")}</div><button class="secondary" data-action="reset-tiles">Neu ordnen</button></div>`;if(type==="sort")return `<div class="sort-game"><div id="sortPicked" class="sort-picked"></div><div class="tile-row">${items.map(x=>`<button data-sort="${x}">${x}</button>`).join("")}</div><button class="secondary" data-action="reset-sort">Zurücksetzen</button></div>`;return `<div class="creative-options">${items.map(x=>`<button data-option="${x}">${x}</button>`).join("")}</div>${type==="pairs"?`<p class="microcopy">Wählt genau zwei passende Aussagen.</p>`:""}`}
function solveOption(btn){const s=DETECTIVE_DATA.spots[state.pending],value=btn.dataset.option;if(s[6]==="pairs"){btn.classList.toggle("active-pick");const values=$$(".active-pick").map(x=>x.dataset.option);if(values.length<2)return;if(values.length>2){btn.classList.remove("active-pick");return}return sameSet(values,s[9])?completeMini():wrongMini()}value===s[9]?completeMini():wrong(btn)}
function pickTile(btn){btn.disabled=true;state.picks.push(btn.dataset.tile);$("#buildTarget").textContent=state.picks.join("");if(state.picks.length===DETECTIVE_DATA.spots[state.pending][9].length)state.picks.join("")===DETECTIVE_DATA.spots[state.pending][9]?completeMini():wrongMini()}
function pickSort(btn){btn.disabled=true;state.picks.push(btn.dataset.sort);$("#sortPicked").innerHTML=state.picks.map(x=>`<span>${x}</span>`).join(" → ");if(state.picks.length===DETECTIVE_DATA.spots[state.pending][9].length)sameSetInOrder(state.picks,DETECTIVE_DATA.spots[state.pending][9])?completeMini():wrongMini()}
function sameSet(a,b){return a.length===b.length&&a.every(x=>b.includes(x))}function sameSetInOrder(a,b){return a.every((x,i)=>x===b[i])}
function wrong(btn){btn.classList.add("wrong");setTimeout(()=>btn.classList.remove("wrong"),500)}function wrongMini(){$("#gameBody").classList.add("shake");setTimeout(()=>{$("#gameBody").classList.remove("shake");resetMini()},500)}
function resetMini(){state.picks=[];const s=DETECTIVE_DATA.spots[state.pending];$("#gameBody").innerHTML=miniHtml(s)}
function completeMini(){const s=DETECTIVE_DATA.spots[state.pending];state.found.add(state.pending);addScore(100);logEvent("Abzeichen gesichert",s[0]);state.pending=null;state.picks=[];$("#gameBody").innerHTML=`<div class="earned"><img src="assets/collectibles/${s[3]}" alt="${s[0]}"><h2>Abzeichen gesichert! +100</h2><p>Das Symbol wandert in eure Sammeltruhe.</p><button class="primary" data-action="close-mini">Weiter suchen</button></div>`;update()}
function update(){renderSpots();$("#chestCount").textContent=state.found.size;$("#progressText").textContent=`${state.found.size} / 12 Abzeichen`;$("#progressFill").style.width=`${state.found.size/12*100}%`;$("#guideText").textContent=`Ihr habt ${state.found.size} Erinnerungsabzeichen. Wenn ihr feststeckt, nutzt den Hinweis-Button.`}
function closeMini(){$("#gameDialog").close();if(chapterDone())chapterTransition()}
function openChest(){$("#chestGrid").innerHTML=DETECTIVE_DATA.spots.map((s,i)=>state.found.has(i)?`<div class="chest-piece"><img src="assets/collectibles/${s[3]}" alt="${s[0]}"><b>${s[0]}</b>${state.avatar===4?`<small>${s[4]}</small>`:""}</div>`:`<div class="chest-piece locked">?</div>`).join("");$("#chestDialog").showModal()}
function giveHint(){if(state.level==="bonus")return giveBonusHint();const open=DETECTIVE_DATA.chapters[state.chapter].ids.map(i=>[DETECTIVE_DATA.spots[i],i]).filter(x=>!state.found.has(x[1]));if(!open.length)return;const [s,i]=open[state.hints%open.length],steps=s[5].split(" | "),step=state.hintSteps[i]||0;state.hintSteps[i]=Math.min(step+1,steps.length-1);state.hints++;addScore(-20);openDialog(`Hinweisstufe ${step+1} von ${steps.length}`,s[0],`${steps[step]} Für einen Hinweis werden 20 Punkte abgezogen.`,`<button class="primary" data-action="close-dialog">Ich suche weiter</button>`)}
function usePower(){if(state.level==="bonus")return giveBonusHint();const a=state.avatar;if(a===0)return say("Adlerblick","Deine Suchflächen sind bereits etwas größer.");if(a===1)return say("Frageprofi","Dein Joker erscheint bei einer schwierigen Abschlussfrage.");if(a===4)return say("Supergedächtnis","Öffne die Truhe: Dort stehen deine zusätzlichen Merksätze.");if(a===3)return say("Fehlspur-Check",state.fakes.size?`Du hast schon ${state.fakes.size} Fehlspur${state.fakes.size===1?"":"en"} erkannt.`:"Bisher habt ihr keine Fehlspur angetippt.");if(state.powerUses<1)return say("Spezialfähigkeit","Deine drei Einsätze sind verbraucht.");state.powerUses--;const open=DETECTIVE_DATA.chapters[state.chapter].ids.map(i=>[DETECTIVE_DATA.spots[i],i]).filter(x=>!state.found.has(x[1]));const [s,i]=open[Math.floor(Math.random()*open.length)];if(a===2){const b=$(`[data-spot="${i}"][data-fake="false"]`);b.classList.add("flash");setTimeout(()=>b.classList.remove("flash"),1800);say("Spürnase","Eine echte Spur leuchtet ganz kurz auf.")}else say("Richtungstipp",`Schaut ${s[1]<35?"links":s[1]>65?"rechts":"in der Mitte"} im Bild genauer hin.`)}
function say(title,text){openDialog(DETECTIVE_DATA.avatars[state.avatar].skill,title,text,`<button class="primary" data-action="close-dialog">Verstanden</button>`)}
function chapterDone(){return DETECTIVE_DATA.chapters[state.chapter].ids.every(i=>state.found.has(i))}
function mapHtml(){return `<div class="map-strip">${DETECTIVE_DATA.chapters.map((chapter,i)=>`<div class="map-piece${state.mapPieces.has(i)?" earned-map":""}">${state.mapPieces.has(i)?`<img src="assets/maps/${chapter.map}" alt="${chapter.title}">`:"?"}<small>Kartenteil ${i+1}</small></div>`).join("")}</div>`}
function chapterTransition(){const chapter=DETECTIVE_DATA.chapters[state.chapter];openDialog("Kapitelspuren vollständig",chapter.title,`${chapter.outro} Bevor ihr das Fragment erhaltet, müsst ihr noch eine größere Kapitelprüfung lösen.`,`<button class="primary" data-action="chapter-game">Kapitelprüfung öffnen</button>`)}
function renderChapterGame(){const g=DETECTIVE_DATA.chapterGames[state.chapter];state.chapterPicks=[];if($("#dialog").open)$("#dialog").close();$("#gameTitle").textContent=g.title;$("#gameIntro").textContent=`${g.intro} ${g.question}`;$("#gameBody").innerHTML=`<div class="sort-picked" id="chapterPicked"></div><div class="creative-options">${shuffle(g.items).map(x=>`<button data-chapter-pick="${x}">${x}</button>`).join("")}</div><p class="microcopy">${g.type==="order"?"Achtet auf die Reihenfolge. Ihr könnt eure Auswahl jederzeit zurücksetzen.":"Wählt alle passenden Begriffe."}</p>${g.type==="order"?`<button class="secondary" data-action="reset-chapter-game">Auswahl zurücksetzen</button>`:""}`;if(!$("#gameDialog").open)$("#gameDialog").showModal()}
function pickChapter(btn){const g=DETECTIVE_DATA.chapterGames[state.chapter];if(g.type==="select"){btn.classList.toggle("active-pick");state.chapterPicks=$$("[data-chapter-pick].active-pick").map(x=>x.dataset.chapterPick);if(state.chapterPicks.length===g.answers.length){sameSet(state.chapterPicks,g.answers)?completeChapterGame():wrongChapter()}}else{btn.disabled=true;state.chapterPicks.push(btn.dataset.chapterPick);$("#chapterPicked").textContent=state.chapterPicks.join(" → ");if(state.chapterPicks.length===g.answers.length){sameSetInOrder(state.chapterPicks,g.answers)?completeChapterGame():wrongChapter()}}}
function wrongChapter(){$("#gameBody").classList.add("shake");$("#chapterPicked").textContent="Noch nicht richtig. Versucht eine andere Reihenfolge.";setTimeout(()=>renderChapterGame(),900)}
function completeChapterGame(){const chapter=DETECTIVE_DATA.chapters[state.chapter];state.mapPieces.add(state.chapter);addScore(150);logEvent("Kapitelprüfung gelöst",chapter.title);$("#gameBody").innerHTML=`<div class="earned"><img class="map-earned" src="assets/maps/${chapter.map}" alt="Kartenfragment ${chapter.title}"><h2>Kartenfragment gesichert! +150</h2><p>Ein weiterer Teil des Archivgeheimnisses wird sichtbar.</p><button class="primary" data-action="${state.chapter===2?"start-quiz":"next-chapter"}">${state.chapter===2?"Karte zusammensetzen":"Nächstes Kapitel"}</button></div>`}
function closeOpenDialogs(){["#dialog","#gameDialog","#chestDialog"].forEach(selector=>{const dialog=$(selector);if(dialog.open)dialog.close()})}
function nextChapter(){closeOpenDialogs();state.chapter++;logEvent("Kapitel gestartet",DETECTIVE_DATA.chapters[state.chapter].title);const chapter=DETECTIVE_DATA.chapters[state.chapter];$("#roomKicker").textContent=`Kapitel ${state.chapter+1} von 3`;$("#roomTitle").textContent=chapter.title;renderSpots();speakerDialog(chapter)}
function speakerDialog(chapter){$("#dialogAvatar").src=chapter.image;$("#dialogKicker").textContent=`Kapitel ${state.chapter+1} von 3 · ${chapter.speaker}`;$("#dialogTitle").textContent=chapter.title;$("#dialogText").textContent=chapter.intro;$("#dialogTask").innerHTML=`<button class="primary" data-action="close-dialog">Kapitel starten</button>`;$("#dialog").showModal()}
function startQuiz(){screen("challengeScreen");state.quiz=0;renderQuiz()}function renderQuiz(){const q=DETECTIVE_DATA.quiz[state.quiz];$("#challengeKicker").textContent="Der Schlüsseltest";$("#challengeTitle").textContent="Warum sind diese Abzeichen wichtig?";$("#challengeIntro").textContent="Pfarrer Falk: „Die Archivtruhe öffnet sich nur, wenn ihr die Bedeutung eurer Funde versteht.“";$("#challengeBody").innerHTML=`<article class="challenge-card"><h2>${q[0]}</h2><div class="answers">${q[1].map((a,i)=>`<button data-quiz="${i}">${a}</button>`).join("")}</div>${state.avatar===1&&state.joker?`<button class="joker" data-action="joker">Linas Antwort-Joker nutzen</button>`:""}</article>`}
function answerQuiz(btn){const q=DETECTIVE_DATA.quiz[state.quiz],ok=+btn.dataset.quiz===q[2];btn.classList.add(ok?"right":"wrong");if(!ok)return;addScore(50);setTimeout(()=>{state.quiz++;state.quiz<DETECTIVE_DATA.quiz.length?renderQuiz():renderKeyPuzzle()},400)}function joker(){state.joker=false;const q=DETECTIVE_DATA.quiz[state.quiz];$$("[data-quiz]").find(b=>+b.dataset.quiz!==q[2]).classList.add("removed")}
function renderKeyPuzzle(){$("#challengeKicker").textContent="Archivrätsel 1";$("#challengeTitle").textContent="Welcher Schlüssel passt zur Karte?";$("#challengeIntro").textContent="Die drei Kartenteile zeigen Musik, Kreuz und Stern. Wählt den Schlüssel mit allen drei Zeichen.";$("#challengeBody").innerHTML=`<article class="challenge-card center">${mapHtml()}<div class="key-grid"><button data-key="wrong">🔑<small>♬ · □ · ✦</small></button><button data-key="right">🔑<small>♬ · ✝ · ✦</small></button><button data-key="wrong">🔑<small>○ · ✝ · △</small></button></div></article>`}
function chooseKey(btn){if(btn.dataset.key!=="right"){btn.classList.add("wrong");return}addScore(150);btn.classList.add("right");setTimeout(renderArchiveSort,450)}
function renderArchiveSort(){state.archiveSort=[];$("#challengeKicker").textContent="Archivrätsel 2";$("#challengeTitle").textContent="Ordnet die Karte im Archiv";$("#challengeIntro").textContent="Tippt die Begriffe in dieser Reihenfolge an: zuerst Gemeinschaft, dann Geschichten und Zeichen, zuletzt Hoffnung und Farben.";$("#challengeBody").innerHTML=`<article class="challenge-card"><div class="sort-picked" id="archivePicked"></div><div class="tile-row">${shuffle(["Gemeinschaft","Geschichten und Zeichen","Hoffnung und Farben"]).map(x=>`<button data-archive-sort="${x}">${x}</button>`).join("")}</div></article>`}
function pickArchive(btn){btn.disabled=true;state.archiveSort.push(btn.dataset.archiveSort);$("#archivePicked").textContent=state.archiveSort.join(" → ");if(state.archiveSort.length===3){if(sameSetInOrder(state.archiveSort,["Gemeinschaft","Geschichten und Zeichen","Hoffnung und Farben"])){addScore(150);setTimeout(renderBonus,450)}else setTimeout(renderArchiveSort,500)}}
function renderBonus(){screen("gameScreen");state.level="bonus";logEvent("Bonuslevel gestartet","Katholische Kirche vergleichen");state.zoom=1;$("#roomStage").style.width="100%";$("#roomStage>img").src="assets/catholic-room.png";$("#roomKicker").textContent="Bonuslevel";$("#roomTitle").textContent="Katholische Kirche vergleichen";$("#progressText").textContent="0 / 6 Vergleichsspuren";$("#progressFill").style.width="0";renderSpots();openBonusIntro()}
function openBonusIntro(){$("#dialogAvatar").src="assets/speakers/fuehrerin-clara.png";$("#dialogKicker").textContent="Bonuslevel · Kirchenführerin Clara";$("#dialogTitle").textContent="Eine zweite Kirche, neue Spuren";$("#dialogText").textContent="Clara: „Willkommen. Vieles kommt euch bekannt vor. Sucht sechs zusätzliche Dinge, die in einer katholischen Kirche eine besondere Rolle spielen.“";$("#dialogTask").innerHTML=`<button class="primary" data-action="close-dialog">Bonuslevel starten</button>`;$("#dialog").showModal()}
function renderBonusSpots(){$("#hotspotLayer").innerHTML=DETECTIVE_DATA.bonus.map((x,i)=>`<button class="hotspot${state.bonusFound.has(i)?" revealed":""}" style="left:${x[3]}%;top:${x[4]}%" data-bonus-spot="${i}" aria-label="${state.bonusFound.has(i)?x[0]:"Vergleichsspur untersuchen"}">${state.bonusFound.has(i)?"✓":""}</button>`).join("")}
function discoverBonus(btn){const i=+btn.dataset.bonusSpot,x=DETECTIVE_DATA.bonus[i];if(state.bonusFound.has(i))return;state.bonusFound.add(i);addScore(50);logEvent("Vergleichsspur entdeckt",x[0]);renderBonusSpots();$("#progressText").textContent=`${state.bonusFound.size} / 6 Vergleichsspuren`;$("#progressFill").style.width=`${state.bonusFound.size/6*100}%`;$("#dialogAvatar").src="assets/speakers/fuehrerin-clara.png";$("#dialogKicker").textContent="Vergleichsspur entdeckt";$("#dialogTitle").textContent=x[0];$("#dialogText").textContent=`Clara: „${x[2]}“`;$("#dialogTask").innerHTML=state.bonusFound.size===6?`<button class="primary" data-action="finish">Archivnotiz lesen</button>`:`<button class="primary" data-action="close-dialog">Weiter vergleichen</button>`;$("#dialog").showModal()}
function giveBonusHint(){const i=DETECTIVE_DATA.bonus.findIndex((x,i)=>!state.bonusFound.has(i));if(i<0)return;const x=DETECTIVE_DATA.bonus[i];state.hints++;addScore(-20);openDialog("Claras Hinweis",x[0],`Clara: „Sucht ${x[3]<35?"links":x[3]>65?"rechts":"in der Mitte"} im Kirchenraum etwas genauer.“ Für einen Hinweis werden 20 Punkte abgezogen.`,`<button class="primary" data-action="close-dialog">Weiter suchen</button>`)}
function overviewCards(){const main=DETECTIVE_DATA.spots.map(s=>`<div class="overview-card"><img src="assets/collectibles/${s[3]}" alt="${s[0]}"><b>${s[0]}</b><small>${s[4]}</small></div>`).join(""),bonus=DETECTIVE_DATA.bonus.map(s=>`<div class="overview-card"><img src="assets/bonus/${s[1]}" alt="${s[0]}"><b>${s[0]}</b><small>${s[2]}</small></div>`).join("");return `<h2>Evangelische Kirche</h2><div class="overview-grid">${main}</div><h2>Katholische Vergleichsspuren</h2><div class="overview-grid">${bonus}</div>`}
function rank(){return state.score>=2100?"Archivprofi":state.score>=1650?"Spurenspezialist":state.score>=1200?"Kirchendetektiv":"Aufmerksamer Entdecker"}
function badgeHtml(){const badges=[["🔍","Adlerauge",state.hints===0],["🧭","Ausdauer",state.found.size===12],["🗺","Kartensammler",state.mapPieces.size===3],["🤝","Vergleichsprofi",state.bonusFound.size===6],["⏱","Tempo-Team",state.timed&&state.seconds>0]];return `<div class="badge-row">${badges.filter(x=>x[2]).map(x=>`<span>${x[0]} ${x[1]}</span>`).join("")}</div>`}
function renderCompareGame(){if($("#dialog").open)$("#dialog").close();screen("challengeScreen");$("#challengeKicker").textContent="Archivrätsel 3";$("#challengeTitle").textContent="Claras Vergleichsarchiv";$("#challengeIntro").textContent="Clara: „Zum Abschluss braucht das Archiv noch eine genaue Einordnung. Tippt jeweils auf die passende Schublade.“";$("#challengeBody").innerHTML=`<article class="challenge-card"><div class="compare-list">${[["Kirchenbänke","beide"],["Taufbecken","beide"],["Tabernakel","katholisch"],["Marienfigur","katholisch"],["Orgel","beide"],["Beichtstuhl","katholisch"]].map(x=>`<div class="compare-row" data-compare-answer="${x[1]}"><b>${x[0]}</b><button data-compare="beide">in beiden</button><button data-compare="katholisch">zusätzliche katholische Spur</button></div>`).join("")}</div></article>`}
function answerCompare(btn){const row=btn.closest(".compare-row");if(btn.dataset.compare!==row.dataset.compareAnswer){btn.classList.add("wrong");return}row.classList.add("done");row.querySelectorAll("button").forEach(x=>x.disabled=true);btn.classList.add("right");if($$(".compare-row.done").length===6){addScore(200);setTimeout(finish,500)}}
function finish(){if($("#dialog").open)$("#dialog").close();screen("challengeScreen");logEvent("Spiel abgeschlossen","Codewort freigeschaltet");$("#challengeKicker").textContent="Archiv geöffnet";$("#challengeTitle").textContent="Der richtige Schlüssel passt";$("#challengeIntro").textContent="Pfarrer Falk: „Besondere Orte und Zeichen helfen Menschen beim Erinnern, Feiern, Hoffen und Nachdenken. In verschiedenen Religionen sehen sie unterschiedlich aus. Respektvolle Neugier verbindet uns.“";$("#challengeBody").innerHTML=`<article class="challenge-card center"><img class="pastor-end" src="assets/pastor-falk.png" alt="Pfarrer Falk"><h2>Detektivrang: ${rank()}</h2><div class="final-score">★ ${state.score} Punkte</div>${badgeHtml()}<div class="codeword">F7-KOMET-29</div><p>Schickt das Codewort über Teams an eure Lehrkraft. Verratet es nicht den nächsten Ermittlungsgruppen.</p><button class="primary" data-action="download-protocol">Lernprotokoll für Teams herunterladen</button></article><section class="overview">${overviewCards()}</section>`;saveProtocol()}
function revealNearby(x,y){let nearest=null,best=58;$$(".hotspot:not(.revealed)").forEach(spot=>{const r=spot.getBoundingClientRect(),distance=Math.hypot(x-(r.left+r.width/2),y-(r.top+r.height/2));if(distance<best){best=distance;nearest=spot}});$$(".hotspot.sensed").forEach(spot=>spot.classList.remove("sensed"));if(nearest)nearest.classList.add("sensed")}
function lightAndZoom(){const box=$("#roomViewport"),stage=$("#roomStage"),light=$("#flashlight");let d=0,z=1;const dist=e=>Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY),move=(x,y)=>{const r=stage.getBoundingClientRect();light.style.left=`${x-r.left}px`;light.style.top=`${y-r.top}px`;light.classList.add("on");revealNearby(x,y)};box.addEventListener("pointermove",e=>move(e.clientX,e.clientY));box.addEventListener("pointerleave",()=>{$$(".hotspot.sensed").forEach(spot=>spot.classList.remove("sensed"));light.classList.remove("on")});box.addEventListener("touchstart",e=>{if(e.touches.length===1)move(e.touches[0].clientX,e.touches[0].clientY);if(e.touches.length===2){d=dist(e);z=state.zoom}},{passive:true});box.addEventListener("touchmove",e=>{if(e.touches.length===1)move(e.touches[0].clientX,e.touches[0].clientY);if(e.touches.length===2){e.preventDefault();state.zoom=Math.max(1,Math.min(2.5,z*dist(e)/d));stage.style.width=`${state.zoom*100}%`;$("#zoomLabel").textContent=`${Math.round(state.zoom*100)} %`}},{passive:false});box.addEventListener("touchend",e=>{if(!e.touches.length){$$(".hotspot.sensed").forEach(spot=>spot.classList.remove("sensed"));light.classList.remove("on")}})}
renderAvatars();selectAvatar(0);tap("[data-action='show-avatars']",()=>screen("avatarScreen"));tap("[data-avatar]",b=>selectAvatar(+b.dataset.avatar));tap("[data-action='start-game']",()=>{state.timed=$("#timeChallenge").checked;startTimer();logEvent("Spiel gestartet",DETECTIVE_DATA.avatars[state.avatar].name);screen("gameScreen");renderSpots();lightAndZoom();speakerDialog(DETECTIVE_DATA.chapters[0])});tap("[data-spot]",investigate);tap("[data-bonus-spot]",discoverBonus);tap("[data-action='open-mini']",startMini);tap("[data-option]",solveOption);tap("[data-tile]",pickTile);tap("[data-sort]",pickSort);tap("[data-chapter-pick]",pickChapter);tap("[data-action='chapter-game'],[data-action='reset-chapter-game']",renderChapterGame);tap("[data-action='reset-tiles'],[data-action='reset-sort']",resetMini);tap("[data-action='close-mini']",closeMini);tap("[data-action='close-dialog']",()=>$("#dialog").close());tap("[data-action='next-chapter']",nextChapter);tap("[data-action='start-quiz']",()=>{ $("#gameDialog").open&&$("#gameDialog").close();$("#dialog").open&&$("#dialog").close();startQuiz()});tap("[data-action='open-chest']",openChest);tap("[data-action='close-chest']",()=>$("#chestDialog").close());tap("[data-action='hint']",giveHint);tap("[data-action='use-power']",usePower);tap("[data-action='download-protocol']",downloadProtocol);tap("[data-quiz]",answerQuiz);tap("[data-key]",chooseKey);tap("[data-archive-sort]",pickArchive);tap("[data-compare]",answerCompare);tap("[data-action='joker']",joker);tap("[data-action='finish']",renderCompareGame);
