"use strict";
const DETECTIVE_DATA={
 chapters:[
  {title:"Gemeinschaft entdecken",speaker:"Pfarrer Falk",image:"assets/pastor-falk.png",map:"gemeinschaft.png",ids:[0,1,11,7],intro:"Pfarrer Falk: „Das erste Kartenteil zeigt eine Bank und Notenlinien. Eine Kirche ist für viele Menschen ein Ort, an dem sie nicht allein bleiben. Sie treffen sich, hören zu, singen und feiern gemeinsam. Findet vier Spuren, die davon erzählen.“",outro:"Pfarrer Falk: „Sehr gut. Ihr habt entdeckt: Gemeinschaft entsteht durch Zusammenkommen, Musik, gemeinsame Lieder und Rituale wie die Taufe. Hinter der Orgel habe ich das erste echte Kartenfragment gefunden. Lena erkennt darauf eine Melodie.“"},
  {title:"Geschichten und Zeichen",speaker:"Kirchenmusikerin Lena",image:"assets/speakers/musik-lena.png",map:"geschichten.png",ids:[2,3,5,8],intro:"Lena: „Hört euch die Karte einmal mit den Augen an: Nach den Noten folgen ein Tisch, ein Buch, ein Kreuz und ein erhöhter Ort zum Sprechen. Menschen geben wichtige Geschichten nicht nur mündlich weiter. Sie lesen, erinnern, deuten und fragen nach. Findet die vier passenden Spuren.“",outro:"Lena: „Jetzt seht ihr, wie Texte und Zeichen zusammenwirken: Die Bibel erzählt, das Kreuz erinnert, am Altar wird gefeiert und von der Kanzel wird über das Leben nachgedacht. Mara hat das dritte Fragment zwischen farbigen Karten entdeckt.“"},
  {title:"Hoffnung und Farben",speaker:"Gemeindepädagogin Mara",image:"assets/speakers/paedagogin-mara.png",map:"hoffnung.png",ids:[4,6,9,10],intro:"Mara: „Manche Dinge erklären sich nicht nur mit Worten. Licht, Farben und Feste können zeigen, was Menschen hoffen. Achtet auf kleine und große Lichter, auf farbige Stoffe und Fenster. Findet die letzten vier Spuren.“",outro:"Mara: „Die Karte ist vollständig. Kerzen, Osterkerze, Paramente und Fenster machen Hoffnung, Feste und Zeiten sichtbar. Jetzt könnt ihr prüfen, welcher Schlüssel wirklich zum Archiv gehört.“"}
 ],
 avatars:[
  {name:"Mika",skill:"Adlerblick",help:"Deine unsichtbaren Suchflächen sind etwas größer."},
  {name:"Lina",skill:"Frageprofi",help:"Bei einer Abschlussfrage kannst du eine falsche Antwort entfernen."},
  {name:"Sam",skill:"Spürnase",help:"Deine Spezialfähigkeit lässt eine offene Spur kurz aufleuchten."},
  {name:"Nour",skill:"Fehlspur-Check",help:"Du erfährst, wie viele Fehlspuren du bereits erkannt hast."},
  {name:"Jun",skill:"Supergedächtnis",help:"In der Sammeltruhe siehst du zusätzliche Merksätze."},
  {name:"Romy",skill:"Richtungssinn",help:"Du bekommst dreimal einen Tipp zur Gegend einer offenen Spur."}
 ],
 spots:[
  ["Kirchenbänke",28,73,"bank.png","Auf den Kirchenbänken sitzen Menschen während eines Gottesdienstes zusammen. Manche hören einer Predigt zu, andere singen oder beten. Auch Besucherinnen und Besucher, die selbst anders oder gar nicht glauben, dürfen respektvoll Platz nehmen und beobachten.","Sucht im unteren Teil des Raums. | Achtet auf die langen Reihen aus Holz. | Dort können viele Menschen gemeinsam sitzen.","sort","Bringt die drei Gedanken in eine sinnvolle Reihenfolge.",["ankommen","Platz nehmen","gemeinsam zuhören"],["ankommen","Platz nehmen","gemeinsam zuhören"]],
  ["Orgel",47,18,"orgel.png","Die Orgel ist ein großes Tasteninstrument mit vielen Pfeifen. Luft bringt die Pfeifen zum Klingen. Eine Orgel kann sehr leise, festlich oder mächtig klingen und begleitet häufig den Gemeindegesang.","Hebt euren Blick nach oben. | Sucht viele lange Pfeifen nebeneinander. | Das große Instrument begleitet häufig Lieder.","letters","Setzt den Namen des Instruments zusammen.","ORGEL","ORGEL"],
  ["Altar",48,59,"altar.png","Der Altar ist ein besonderer Tisch im vorderen Bereich der Kirche. In evangelischen Kirchen stehen dort oft eine Bibel, Kerzen und Blumen. Beim Abendmahl erinnert er an Gemeinschaft und an die Geschichte Jesu.","Sucht vorne in der Mitte. | Achtet auf den Tisch mit Tuch, Buch und Kerzen. | Beim Abendmahl spielt dieser besondere Tisch eine wichtige Rolle.","choice","Welche Beschreibung passt zum Fund?",["besonderer Tisch","Instrument mit Pfeifen","Sitzplatz"],"besonderer Tisch"],
  ["Bibel",47,56,"bibel.png","Die Bibel ist eine Sammlung vieler Texte: Geschichten, Gebete, Lieder, Briefe und Gedanken. Christinnen und Christen lesen daraus im Gottesdienst und fragen, was diese Texte für das Leben heute bedeuten können.","Schaut auf den Altar. | Sucht ein aufgeschlagenes Buch. | Aus diesem Buch werden im Gottesdienst Texte vorgelesen.","letters","Ordnet die Buchstaben zu einem wichtigen Buch.","BIBEL","BIBEL"],
  ["Kerzen",41,57,"kerze.png","Kerzen sind mehr als Schmuck. Ihr Licht kann an Hoffnung, Gebet und Trost erinnern. Auch in anderen Religionen und bei weltlichen Gedenkfeiern verwenden Menschen Licht als starkes Zeichen.","Schaut in die Umgebung des Altars. | Achtet auf mehrere kleine Flammen. | Ihr Licht kann für Hoffnung und Trost stehen.","choice","Welche Idee passt besonders gut zu einer Kerze?",["Hoffnung","Fußball","Fahrplan"],"Hoffnung"],
  ["Großes Kreuz",48,48,"kreuz.png","Das Kreuz ist ein zentrales christliches Zeichen. Es erinnert an die Geschichte Jesu, an Leid und zugleich an die Hoffnung, dass Tod und Verzweiflung nicht das letzte Wort haben.","Schaut über den Altar. | Sucht in der Mitte der Wand zwei Balken. | Dieses christliche Zeichen erinnert an Jesus.","pairs","Welche zwei Aussagen gehören zum Kreuz?",["christliches Zeichen","erinnert an Jesus","zeigt Liednummern"],["christliches Zeichen","erinnert an Jesus"]],
  ["Osterkerze",64,55,"osterkerze.png","Die Osterkerze ist größer und auffälliger als andere Kerzen. Sie wird an Ostern besonders feierlich entzündet und erinnert an Auferstehung, neues Leben und Hoffnung.","Sucht rechts neben dem Altar. | Achtet auf eine besonders große verzierte Kerze. | Ihr Name verrät, zu welchem Fest sie gehört.","letters","Welche Feier steckt im Namen dieser Kerze?","OSTERN","OSTERN"],
  ["Taufbecken",74,61,"taufbecken.png","Am Taufbecken wird bei einer Taufe Wasser verwendet. Die Taufe erinnert an einen Neuanfang und an die Aufnahme in die christliche Gemeinschaft. Wasser ist dabei ein Zeichen für Leben.","Schaut vorne rechts. | Sucht einen steinernen Gegenstand in der Nähe der Bänke. | Bei einer Taufe wird darin Wasser verwendet.","drop","Was gehört gedanklich in das Taufbecken?",["Wasser","Konfetti","Noten"],"Wasser"],
  ["Kanzel",80,45,"kanzel.png","Die Kanzel ist ein erhöhter Ort zum Sprechen. Von dort wird häufig gepredigt: Ein Bibeltext wird erklärt und mit Fragen aus dem Leben der Menschen verbunden.","Sucht rechts an der Wand. | Achtet auf einen erhöhten Ort mit Treppe. | Von hier aus wird häufig eine Predigt gehalten.","choice","Was geschieht hier häufig?",["Eine Predigt","Ein Fußballspiel","Eine Busfahrt"],"Eine Predigt"],
  ["Paramente",79,42,"parament.png","Paramente sind farbige Tücher an Altar oder Kanzel. Ihre Farben wechseln im Kirchenjahr. Weiß, Grün, Violett oder Rot können zu unterschiedlichen Festen und Zeiten passen.","Schaut auf die Kanzel. | Sucht ein farbiges Tuch. | Seine Farbe kann passend zur Zeit im Kirchenjahr wechseln.","pairs","Wählt zwei passende Merkmale.",["farbiges Tuch","Farbe kann wechseln","Musikinstrument"],["farbiges Tuch","Farbe kann wechseln"]],
  ["Kirchenfenster",89,22,"fenster.png","Kirchenfenster verändern den Raum durch farbiges Licht. Manche zeigen Bilder aus biblischen Geschichten, andere arbeiten mit Mustern. Das Licht wandert im Laufe des Tages durch die Kirche.","Fahrt an den Seitenwänden entlang. | Sucht hohe Fenster mit vielen Farben. | Das Sonnenlicht fällt dort bunt in den Raum.","choice","Was macht dieses Fenster besonders?",["farbiges Licht","es kocht Wasser","es spielt Musik"],"farbiges Licht"],
  ["Liedtafel",6,52,"liedtafel.png","Eine Liedtafel zeigt die Nummern der Lieder, die im Gottesdienst gesungen werden. So können alle im Gesangbuch schnell die richtige Seite finden. In diesem Raum liegt ihre Spur bei der kleinen Infowand.","Schaut links an die Wand. | Sucht eine kleine Tafel in der Nähe der Bankreihen. | Normalerweise stehen dort Nummern für gemeinsame Lieder.","drop","Was würde auf einer Liedtafel stehen?",["Liednummern","Preise","Geburtstage"],"Liednummern"]
 ],
 fakes:[["Wanduhr",4,38],["Regenschirme",9,89],["Rucksack",64,86],["Deckenlampe",48,5],["Blumenvase",54,58],["Infowand",6,58]],
 quiz:[
  ["Was verbindet viele gefundene Spuren?",["Sie helfen Menschen beim Erinnern, Feiern und Nachdenken","Sie sind alle aus Gold","Sie sind nur Dekoration"],0],
  ["Wie erkundet man ein Gotteshaus respektvoll?",["Genau schauen und Fragen stellen","Alles anfassen","Andere auslachen"],0]
 ],
 chapterGames:[
  {title:"Die Karte der Gemeinschaft",intro:"Pfarrer Falk: „Das Fragment öffnet sich nur, wenn ihr erkennt, was Menschen in einer Kirche miteinander verbindet.“",type:"select",question:"Wählt alle drei passenden Begriffe.",items:["gemeinsam singen","zuhören","Taufe","Speisekarte"],answers:["gemeinsam singen","zuhören","Taufe"]},
  {title:"Lenas Zeichenfolge",intro:"Lena: „Die Tinte auf dem zweiten Fragment wird sichtbar, wenn ihr die Orte in eine sinnvolle Reihenfolge bringt.“",type:"order",question:"Tippt zuerst den Ort zum Lesen, dann das Zeichen und zuletzt den Ort zum Erklären an.",items:["Kanzel","Bibel","Kreuz"],answers:["Bibel","Kreuz","Kanzel"]},
  {title:"Maras Farbenarchiv",intro:"Mara: „Das letzte Fragment reagiert auf Licht und Farbe. Findet die richtige Gruppe.“",type:"select",question:"Welche drei Funde machen Hoffnung, Feste oder Farben sichtbar?",items:["Osterkerze","Paramente","Kirchenfenster","Regenschirme"],answers:["Osterkerze","Paramente","Kirchenfenster"]}
 ],
 bonus:[
  ["Weihwasserschale","weihwasser.png","Sie erinnert am Eingang an die Taufe.",7,72],["Kniebank","kniebank.png","Sie kann beim Gebet genutzt werden.",63,82],["Marienfigur","marienfigur.png","Sie erinnert an Maria, die Mutter Jesu.",73,39],["Tabernakel","tabernakel.png","Darin werden geweihte Hostien aufbewahrt.",39,48],["Hostien","hostien.png","Diese kleinen Brote gehören zur Eucharistie.",61,53],["Beichtstuhl","beichtstuhl.png","Hier ist ein vertrauliches Gespräch möglich.",22,43]
 ]
};
