const domains=[
 {name:'Himmel & Donner',desc:'Macht über Wolken, Wind und Blitze',icon:'⚡',pos:'0% 0%',title:'des Himmels'},
 {name:'Meer',desc:'Hüterin oder Hüter der Wellen',icon:'🔱',pos:'50% 0%',title:'der Meere'},
 {name:'Weisheit',desc:'Klare Gedanken und kluge Pläne',icon:'🦉',pos:'100% 0%',title:'der Weisheit'},
 {name:'Licht & Musik',desc:'Kunst, Dichtung und Sonnenlicht',icon:'☀️',pos:'0% 100%',title:'des Lichtes'},
 {name:'Natur & Mond',desc:'Schutz für Tiere, Wälder und Nacht',icon:'🌙',pos:'50% 100%',title:'der Wildnis'},
 {name:'Feuer & Handwerk',desc:'Erfindungen aus Glut und Metall',icon:'🔨',pos:'100% 100%',title:'des Feuers'}
];
const stages=[
 {kicker:'ERSTE ENTSCHEIDUNG',q:'Welche Macht ist deine?',help:'Wähle ein göttliches Gebiet.',items:domains},
 {kicker:'DEIN WESEN',q:'Was zeichnet dich aus?',help:'Stärken bestimmen später deine Möglichkeiten.',items:[['Mutig','Ich stelle mich jeder Gefahr','🦁'],['Klug','Ich löse Probleme mit Köpfchen','🧠'],['Gerecht','Ich beschütze Schwächere','⚖️'],['Wild','Ich folge meinem eigenen Weg','🌿'],['Kreativ','Ich erfinde und gestalte','🎨'],['Listig','Ich finde überraschende Wege','🦊']].map(([name,desc,icon])=>({name,desc,icon}))},
 {kicker:'DEIN HEILIGES TIER',q:'Wer begleitet dich?',help:'Tiere galten oft als Zeichen einer Gottheit.',items:[['Eule','Wachsam und weise','🦉'],['Adler','Stark und weitsichtig','🦅'],['Delfin','Verspielt und hilfsbereit','🐬'],['Hirsch','Frei und flink','🦌'],['Schlange','Geheimnisvoll und klug','🐍'],['Pferd','Treue und Kraft','🐎']].map(([name,desc,icon])=>({name,desc,icon}))},
 {kicker:'DEIN GÖTTLICHES ZEICHEN',q:'Welches Symbol erkennt man sofort?',help:'Symbole machten Gottheiten auf Vasen erkennbar.',items:[['Goldener Schlüssel','Öffnet verborgene Wege','🗝️'],['Leuchtende Fackel','Bringt Licht ins Dunkel','🔥'],['Silberner Schild','Schützt Menschen in Not','🛡️'],['Lorbeerkranz','Zeichen für Ruhm und Sieg','🌿'],['Magische Lyra','Musik besänftigt jedes Herz','🎵'],['Sternenkrug','Schenkt Hoffnung und Mut','🏺']].map(([name,desc,icon])=>({name,desc,icon}))},
 {kicker:'EIN ORT FÜR DICH',q:'Wo steht dein Heiligtum?',help:'Ein Heiligtum war ein besonderer Ort der Verehrung.',items:[['Auf einer Klippe','Hoch über dem Ägäischen Meer','⛰️'],['Im Olivenhain','Zwischen uralten Bäumen','🫒'],['An einer Quelle','Wo klares Wasser entspringt','💧'],['In einer Stadt','Mitten unter den Menschen','🏛️'],['Auf einer Insel','Von blauem Meer umgeben','🏝️'],['In einer Höhle','Still und voller Geheimnisse','🪨']].map(([name,desc,icon])=>({name,desc,icon}))}
];
const trials=[
 {title:'Der Sturm über Thasos',scene:'🌩️ ⛵ 🌊',text:'Ein Fischerboot gerät in einen unnatürlichen Sturm. Die Menschen rufen deinen Namen.',options:[['Beruhige Wind und Wellen','worship',2,'Die Geretteten errichten dir dankbar einen kleinen Altar.'],['Führe das Boot mit einem Zeichen','wisdom',2,'Dein kluges Zeichen weist den sicheren Weg.'],['Zerschmettere den Sturm mit Macht','awe',2,'Der Himmel erbebt – niemand zweifelt mehr an deiner Macht.']]},
 {title:'Der Streit am Heiligtum',scene:'🏛️ ⚔️ 🫒',text:'Zwei Dörfer beanspruchen dieselbe heilige Quelle. Schon werden Schwerter gezogen.',options:[['Lass beide Seiten sprechen','wisdom',2,'Ein gerechter Vertrag beendet den Streit.'],['Teile das Wasser für alle','worship',2,'Das Wunder versorgt beide Dörfer und bringt dir Verehrung.'],['Warne sie mit einem Omen','awe',2,'Dein Omen lässt die Waffen augenblicklich sinken.']]},
 {title:'Das Ungeheuer von Arkadien',scene:'🐉 🌲 🔥',text:'Ein uraltes Ungeheuer bedroht Reisende. Es bewacht jedoch sein einziges Junges.',options:[['Zähme es und schütze das Junge','worship',2,'Aus Furcht wird Vertrauen; das Tier bewacht fortan deinen Tempel.'],['Finde ihm ein fernes Zuhause','wisdom',2,'Eine kluge Lösung rettet Menschen und Tier.'],['Vertreibe es mit göttlicher Kraft','awe',2,'Dein Machtspruch hallt noch lange durch die Berge.']]}
];
const lexicon=[['Anthropomorphe Götter','Griechische Gottheiten wurden meist menschengestaltig dargestellt – mit menschlichen Gefühlen, Stärken und Fehlern.'],['Attribute','Blitz, Dreizack oder Eule halfen dabei, eine Gottheit auf Bildern sofort zu erkennen.'],['Tempel','Ein Tempel galt als Haus der Gottheit. Rituale und Opfer fanden meist am Altar davor statt.'],['Orakel','An Orten wie Delphi deuteten Priesterinnen göttliche Botschaften.'],['Opfergaben','Menschen brachten unter anderem Wein, Öl, Tiere oder kleine Figuren dar.'],['Mythen','Sagen erklärten Natur, Bräuche und menschliche Konflikte – oft in vielen unterschiedlichen Versionen.']];
let stage=0,answers=[],trialIndex=0,stats={worship:0,wisdom:0,awe:0};
const avatarState={shape:'heroic',skin:'bronze',hair:'curls',hairColor:'night',face:'kind',crown:'stars',eye:'ocean',gift:'glow',weapon:'sword',clothColor:'#164f6d'};
const templeState={columns:'marble',setting:'cliff',offering:'olive'};
const skinColors={bronze:'#b97852',olive:'#bd8b62',deep:'#754936',marble:'#e2c6b2',azure:'#65a9bb'},hairColors={night:'#172338',gold:'#d6a735',copper:'#8c402b',silver:'#d8d9d2',sea:'#176e70'},crownIcons={stars:'✦',laurel:'❧',horns:'♈',waves:'≋',none:''},clothColors=['#164f6d','#176d79','#786038','#9a3f32','#375c40','#6b426f'];
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),show=id=>{$$('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active')};
function tone(freq=440){try{const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.frequency.value=freq;o.connect(g);g.connect(a.destination);g.gain.setValueAtTime(.04,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.13);o.start();o.stop(a.currentTime+.13)}catch(e){}}
function progress(label,count){$('#stepLabel').textContent=label;$('#stepCount').textContent=`${count} / 10`;$('#progressBar').style.width=`${count*10}%`}
function render(){const s=stages[stage];$('#chapterNo').textContent=['I','II','III','IV','V'][stage];$('#chapterKicker').textContent=s.kicker;$('#question').textContent=s.q;$('#instruction').textContent=s.help;progress(`ERSCHAFFUNG ${stage+1}`,stage+1);$('#choices').innerHTML=s.items.map((x,i)=>`<button class="choice ${answers[stage]===i?'selected':''}" data-i="${i}">${stage===0?`<div class="choice-img" style="--pos:${x.pos}"></div>`:`<div class="choice-img" style="background-image:none;background:linear-gradient(135deg,#eaf4ee,#d6e8e7);display:grid;place-items:center;font-size:58px">${x.icon}</div>`}<div class="choice-body"><b>${x.name}</b><small>${x.desc}</small></div></button>`).join('');$('#nextBtn').disabled=answers[stage]===undefined;$('#backBtn').style.visibility=stage?'visible':'hidden';updateAvatar();$$('.choice').forEach(b=>b.onclick=()=>{answers[stage]=+b.dataset.i;tone();render();saveGame()})}
function paintAvatar(el=$('#avatar')){const d=domains[answers[0]??0],weapons={sword:'⚔️',staff:'🪄',bow:'🏹',hammer:'🔨',none:''};Object.entries(avatarState).forEach(([k,v])=>el.dataset[k]=v);el.style.setProperty('--skin',skinColors[avatarState.skin]);el.style.setProperty('--hair',hairColors[avatarState.hairColor]);el.style.setProperty('--cloth',avatarState.clothColor||clothColors[answers[0]??0]);el.querySelector('.a-emblem').textContent=d.icon;el.querySelector('.a-crown').textContent=crownIcons[avatarState.crown];el.querySelector('.a-weapon').textContent=weapons[avatarState.weapon]}
function updateAvatar(){paintAvatar();const labels=answers.map((a,i)=>stages[i].items[a]?.name).filter(Boolean);$('#traits').innerHTML=labels.length?labels.map(x=>`<span>${x}</span>`).join(''):'<span>Noch unbeschrieben</span>'}
const editorFields={shape:'shapeSelect',skin:'skinSelect',hair:'hairSelect',hairColor:'hairColorSelect',face:'faceSelect',crown:'crownSelect',eye:'eyeSelect',gift:'giftSelect',weapon:'weaponSelect',clothColor:'clothColorSelect'};
Object.entries(editorFields).forEach(([key,id])=>{$('#'+id).onchange=e=>{avatarState[key]=e.target.value;paintAvatar();tone();saveGame()}});
$('#randomBtn').onclick=()=>{Object.entries(editorFields).forEach(([key,id])=>{const s=$('#'+id);s.selectedIndex=Math.floor(Math.random()*s.options.length);avatarState[key]=s.value});paintAvatar();tone(520);saveGame()};
function updateStats(){$('#reputation').hidden=false;Object.keys(stats).forEach(k=>$('#'+k+'Stat').textContent=stats[k])}
function saveGame(){try{const current=document.querySelector('.screen.active')?.id||'gameScreen';localStorage.setItem('goetterwerkstatt-save',JSON.stringify({stage,answers,trialIndex,stats,avatarState,templeState,name:$('#nameInput').value,current}));$('#resumeBtn').hidden=false}catch(e){}}
function loadGame(){try{const d=JSON.parse(localStorage.getItem('goetterwerkstatt-save'));if(!d)return;stage=d.stage??0;answers=d.answers||[];trialIndex=d.trialIndex||0;stats=Object.assign(stats,d.stats);Object.assign(avatarState,d.avatarState);Object.assign(templeState,d.templeState);$('#nameInput').value=d.name||'';Object.entries(editorFields).forEach(([k,id])=>$('#'+id).value=avatarState[k]);if(d.current==='templeScreen')showTemple();else if(d.current==='adventureScreen'){updateStats();trialIndex<trials.length?showTrial():showQuiz()}else if(d.current==='quizScreen'){updateStats();showQuiz()}else{show('#gameScreen');render()}}catch(e){}}
$('#startBtn').onclick=()=>{show('#gameScreen');render()};$('#resumeBtn').onclick=loadGame;
$('#nameInput').oninput=saveGame;
$('#nextBtn').onclick=()=>{if(!$('#nameInput').value.trim()&&stage===4){$('#nameInput').focus();$('#hint').textContent='Gib deiner Gottheit noch einen Namen!';return}if(stage<4){stage++;render();scrollTo(0,0)}else{showTemple()}saveGame()};
$('#backBtn').onclick=()=>{if(stage){stage--;render()}};
function showTemple(){show('#templeScreen');progress('HEILIGTUM',6);$('#templeMark').textContent=domains[answers[0]].icon;renderTemple()}
function renderTemple(){$('#templePreview').dataset.columns=templeState.columns;$('#templePreview').dataset.setting=templeState.setting;$('#offeringIcon').textContent={olive:'🫒',incense:'♨️',honey:'🍯'}[templeState.offering]}
[['columnSelect','columns'],['settingSelect','setting'],['offeringSelect','offering']].forEach(([id,key])=>{$('#'+id).onchange=e=>{templeState[key]=e.target.value;renderTemple();saveGame()}});
$('#templeNextBtn').onclick=()=>{trialIndex=0;stats={worship:0,wisdom:0,awe:0};updateStats();showTrial()};
function showTrial(){const t=trials[trialIndex];show('#adventureScreen');progress(`PRÜFUNG ${trialIndex+1}`,7+trialIndex);$('#trialKicker').textContent=`KAPITEL ${['I','II','III'][trialIndex]} · DEINE SAGE`;$('#trialTitle').textContent=t.title;$('#trialScene').textContent=`${domains[answers[0]].icon} ${t.scene}`;$('#trialText').textContent=t.text;$('#consequence').textContent='';$('#trialOptions').innerHTML=t.options.map((o,i)=>`<button data-i="${i}"><b>${o[0]}</b><br><small>${o[1]==='worship'?'Verehrung':o[1]==='wisdom'?'Weisheit':'Ehrfurcht'} steigt</small></button>`).join('');$$('#trialOptions button').forEach(b=>b.onclick=()=>resolveTrial(+b.dataset.i))}
function resolveTrial(i){const o=trials[trialIndex].options[i];stats[o[1]]+=o[2];updateStats();$('#consequence').textContent=o[3];$$('#trialOptions button').forEach(b=>b.disabled=true);tone(620);trialIndex++;saveGame();setTimeout(()=>{trialIndex<trials.length?showTrial():showQuiz()},1000)}
function showQuiz(){show('#quizScreen');progress('ATHENES PRÜFUNG',10)}
$$('.quiz-options button').forEach(b=>b.onclick=()=>{if(b.dataset.correct==='true'){b.style.background='#dcebd6';$('#quizFeedback').textContent='Richtig! Tempel waren heilige Orte der Verehrung. 🏛️';stats.wisdom++;updateStats();setTimeout(finish,700)}else{b.style.background='#f3d7cd';$('#quizFeedback').textContent='Fast! Denk daran: Ein Tempel war ein heiliger Ort.'}});
function finish(){const d=domains[answers[0]],trait=stages[1].items[answers[1]],animal=stages[2].items[answers[2]],symbol=stages[3].items[answers[3]],place=stages[4].items[answers[4]],name=$('#nameInput').value.trim()||'Asterios';const max=Object.keys(stats).sort((a,b)=>stats[b]-stats[a])[0],endings={worship:'Als volksnahe Schutzgottheit erzählen sich die Menschen deinen Namen an jedem Herdfeuer.',wisdom:'Als weise Orakelgottheit suchen Königinnen und Helden deinen Rat.',awe:'Als ehrfurchtgebietende Macht wird dein Zeichen noch über Generationen in Stein gemeißelt.'};$('#resultName').textContent=name;$('#resultTitle').textContent=`Gottheit ${d.title}`;$('#resultSymbol').textContent=`${d.icon} ${animal.icon}`;$('#resultStory').textContent=`${name} ist ${trait.name.toLowerCase()} und wacht über ${d.name}. Begleitet von ${animal.name} trägt die Gottheit ${symbol.name} und wird ${place.name.toLowerCase()} verehrt.`;$('#endingText').textContent=endings[max];$('#resultBadges').innerHTML=[trait.name,animal.name,symbol.name,`♥ ${stats.worship}`,`◆ ${stats.wisdom}`,`✦ ${stats.awe}`].map(x=>`<span>${x}</span>`).join('');const clone=$('#avatar').cloneNode(true);clone.id='resultGodAvatar';$('#resultAvatar').replaceChildren(clone);paintAvatar(clone);show('#resultScreen');try{localStorage.removeItem('goetterwerkstatt-save')}catch(e){}$('#resumeBtn').hidden=true}
function downloadCard(){const c=document.createElement('canvas'),x=c.getContext('2d'),name=$('#resultName').textContent,d=domains[answers[0]];c.width=1000;c.height=630;const g=x.createLinearGradient(0,0,1000,630);g.addColorStop(0,'#123b54');g.addColorStop(1,'#187789');x.fillStyle=g;x.fillRect(0,0,1000,630);x.strokeStyle='#e2a93b';x.lineWidth=12;x.strokeRect(28,28,944,574);x.fillStyle='#fff7df';x.textAlign='center';x.font='28px Georgia';x.fillText('DIE GÖTTERWERKSTATT',500,90);x.font='bold 72px Georgia';x.fillText(name,500,180);x.font='32px Georgia';x.fillStyle='#f1bd52';x.fillText(`Gottheit ${d.title}`,500,230);x.font='110px serif';x.fillText(`${d.icon} ${stages[2].items[answers[2]].icon}`,500,375);x.font='24px Arial';x.fillStyle='#fff7df';x.fillText(`Verehrung ${stats.worship}   ·   Weisheit ${stats.wisdom}   ·   Ehrfurcht ${stats.awe}`,500,470);x.font='italic 22px Georgia';x.fillText('Eine neue Sage des Olymp',500,535);const a=document.createElement('a');a.download=`goetterkarte-${name.toLowerCase().replace(/[^a-z0-9äöü]+/g,'-')}.png`;a.href=c.toDataURL('image/png');a.click()}
$('#downloadBtn').onclick=downloadCard;$('#printBtn').onclick=()=>print();$('#restartBtn').onclick=()=>{stage=0;answers=[];trialIndex=0;stats={worship:0,wisdom:0,awe:0};$('#nameInput').value='';$('#reputation').hidden=true;show('#startScreen');progress('PROLOG',0)};$('#soundBtn').onclick=()=>tone();
$('#lexiconEntries').innerHTML=lexicon.map(([h,p])=>`<article class="lexicon-entry"><b>${h}</b><p>${p}</p></article>`).join('');$('#lexiconBtn').onclick=()=>$('#lexiconDialog').showModal();$('#lexiconClose').onclick=()=>$('#lexiconDialog').close();
try{$('#resumeBtn').hidden=!localStorage.getItem('goetterwerkstatt-save')}catch(e){}
