const db=createDb();let sessionId=getActiveSession()||randomSession(),rows=[],liveChannel=null,teacherPin="";setActiveSession(sessionId);
function renderLinks(){const tablet=sessionUrl("tablet.html",sessionId),board=sessionUrl("tafel.html",sessionId);document.getElementById("teacherSession").textContent=sessionId;document.getElementById("tabletUrl").value=tablet;document.getElementById("openBoard").href=board;document.getElementById("qrImage").src=`https://api.qrserver.com/v1/create-qr-code/?size=260x260&data=${encodeURIComponent(tablet)}`}
function renderGroups(){const groups=new Map();rows.filter(row=>row.sektor!=="finale"&&row.gruppen_id!=="lehrkraft").forEach(row=>{if(!groups.has(row.gruppen_id))groups.set(row.gruppen_id,new Set());groups.get(row.gruppen_id).add(row.sektor)});document.getElementById("teacherGroups").innerHTML=groups.size?[...groups].map(([group,sectors])=>`<div class="group-progress"><b>${group}</b><span>${sectors.size} / ${SECTORS.length}</span><div class="mini-track"><i style="width:${sectors.size/SECTORS.length*100}%"></i></div></div>`).join(""):"<p>Noch keine Gruppe hat eine Station abgeschlossen.</p>";const done=completedSectorIds(rows);document.getElementById("manualUnlock").innerHTML=SECTORS.map(sector=>`<button class="comic-button ${done.has(sector.id)?"done-button":""}" data-unlock="${sector.id}" ${done.has(sector.id)?"disabled":""}>${done.has(sector.id)?"✓ ":""}${sector.name}</button>`).join("");document.querySelectorAll("[data-unlock]").forEach(button=>button.addEventListener("click",()=>unlock(button.dataset.unlock)))}
async function refresh(){rows=await readProgress(db,sessionId);renderGroups()}
async function unlock(sector){await markDone(db,{session_id:sessionId,gruppen_id:"lehrkraft",sektor,status:"erledigt",event_type:"manual"},{teacherPin});await refresh()}
async function sendFinale(){await markDone(db,{session_id:sessionId,gruppen_id:"lehrkraft",sektor:"finale",status:"erledigt",event_type:"finale"},{teacherPin});document.getElementById("startFinale").textContent="Finale gesendet ✓"}
function subscribe(){if(!db)return;if(liveChannel)db.removeChannel(liveChannel);liveChannel=db.channel(`teacher-${sessionId}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"fortschritt",filter:`session_id=eq.${sessionId}`},()=>refresh()).subscribe()}
function startSession(){sessionId=randomSession();rows=[];setActiveSession(sessionId);history.replaceState({}, "", `?session=${sessionId}`);renderLinks();renderGroups();subscribe()}
function openDashboard(){document.getElementById("teacherLogin").classList.add("hidden");document.getElementById("teacherDashboard").classList.remove("hidden");renderLinks();refresh();subscribe()}
document.getElementById("pinForm").addEventListener("submit",event=>{event.preventDefault();teacherPin=document.getElementById("pinInput").value;if(teacherPin!==String(window.BERG_CONFIG?.TEACHER_PIN||"2468")){document.getElementById("pinError").classList.remove("hidden");return}openDashboard()});
document.getElementById("newSession").addEventListener("click",startSession);document.getElementById("startFinale").addEventListener("click",sendFinale);document.getElementById("copyTabletUrl").addEventListener("click",async()=>{const field=document.getElementById("tabletUrl");try{await navigator.clipboard.writeText(field.value);document.getElementById("copyTabletUrl").textContent="Link kopiert ✓"}catch{field.focus();field.select()}});setConnectionStatus(db?"Live verbunden":"Demo-Modus",Boolean(db));
