-- Einmalig im Supabase SQL Editor ausführen.
-- Das Modell bleibt append-only: Browser dürfen nur SELECT und INSERT nutzen.
-- Es werden keine Namen, E-Mails oder sonstigen Personendaten gespeichert.

create table if not exists public.fortschritt (
  id bigint generated by default as identity primary key,
  session_id text not null check (session_id ~ '^[a-z0-9-]{6,32}$'),
  gruppen_id text not null check (gruppen_id ~ '^[a-z0-9_-]{2,24}$'),
  sektor text not null check (sektor in ('kapernaum', 'berg', 'see', 'nazareth', 'tiberias', 'finale', 'control')),
  status text not null check (status = 'erledigt'),
  event_type text not null default 'solved' check (event_type in ('solved', 'manual', 'finale', 'lock', 'unlock', 'groups', 'phase', 'prompt')),
  payload text check (payload is null or char_length(payload) <= 420),
  created_at timestamptz not null default now()
);

-- Migration einer älteren Testtabelle:
alter table public.fortschritt add column if not exists session_id text;
alter table public.fortschritt add column if not exists event_type text not null default 'solved';
alter table public.fortschritt add column if not exists payload text;
update public.fortschritt set session_id = 'legacy-test' where session_id is null;
alter table public.fortschritt alter column session_id set not null;
alter table public.fortschritt drop constraint if exists fortschritt_session_id_check;
alter table public.fortschritt drop constraint if exists fortschritt_sektor_check;
alter table public.fortschritt drop constraint if exists fortschritt_status_check;
alter table public.fortschritt drop constraint if exists fortschritt_event_type_check;
alter table public.fortschritt drop constraint if exists fortschritt_payload_check;
alter table public.fortschritt add constraint fortschritt_session_id_check check (session_id ~ '^[a-z0-9-]{6,32}$');
alter table public.fortschritt add constraint fortschritt_sektor_check check (sektor in ('kapernaum', 'berg', 'see', 'nazareth', 'tiberias', 'finale', 'control'));
alter table public.fortschritt add constraint fortschritt_status_check check (status = 'erledigt');
alter table public.fortschritt add constraint fortschritt_event_type_check check (event_type in ('solved', 'manual', 'finale', 'lock', 'unlock', 'groups', 'phase', 'prompt'));
alter table public.fortschritt add constraint fortschritt_payload_check check (payload is null or char_length(payload) <= 420);
delete from public.fortschritt a using public.fortschritt b
where a.id > b.id
  and a.session_id = b.session_id
  and a.gruppen_id = b.gruppen_id
  and a.sektor = b.sektor
  and a.event_type in ('solved', 'manual', 'finale')
  and b.event_type in ('solved', 'manual', 'finale');
drop index if exists fortschritt_gruppe_station_unique;
create unique index if not exists fortschritt_gruppe_station_unique on public.fortschritt (session_id, gruppen_id, sektor)
  where event_type in ('solved', 'manual', 'finale');

-- Nur für die optionale Edge Function: serverseitiges Rate-Limit.
create table if not exists public.fortschritt_rate_limit (
  id bigint generated by default as identity primary key,
  client_key text not null,
  created_at timestamptz not null default now()
);
alter table public.fortschritt_rate_limit enable row level security;
revoke all on table public.fortschritt_rate_limit from anon;

alter table public.fortschritt enable row level security;
revoke all on table public.fortschritt from anon;
grant select, insert on table public.fortschritt to anon;
grant usage, select on sequence public.fortschritt_id_seq to anon;

drop policy if exists "Anon darf Fortschritt lesen" on public.fortschritt;
create policy "Anon darf Fortschritt lesen" on public.fortschritt
  for select to anon using (session_id is not null);

drop policy if exists "Anon darf erledigte Stationen eintragen" on public.fortschritt;
create policy "Anon darf erledigte Stationen eintragen" on public.fortschritt
  for insert to anon with check (
    session_id ~ '^[a-z0-9-]{6,32}$'
    and gruppen_id ~ '^[a-z0-9_-]{2,24}$'
    and sektor in ('kapernaum', 'berg', 'see', 'nazareth', 'tiberias', 'finale', 'control')
    and status = 'erledigt'
    and event_type in ('solved', 'manual', 'finale', 'lock', 'unlock', 'groups', 'phase', 'prompt')
    and (payload is null or char_length(payload) <= 420)
  );

-- Falls die Tabelle noch nicht zur Realtime-Publikation gehört:
-- alter publication supabase_realtime add table public.fortschritt;
