const TASKS=[
  {id:"selig-1",sector:"berg",type:"sort",difficulty:1,title:"Seligpreisungen ordnen",story:"Die Karten der ersten Rede Jesu sind durcheinander geraten.",source:"Mt 5,3-12: Selig sind u. a. Arme vor Gott, Trauernde, Sanftmütige, Barmherzige und Friedensstifter.",question:"Bringt die vier Seligpreisungen in eine sinnvolle Textnähe-Reihenfolge.",items:["Selig sind, die arm sind vor Gott","Selig sind, die Leid tragen","Selig sind die Sanftmütigen","Selig sind die Friedensstifter"],correct:["Selig sind, die arm sind vor Gott","Selig sind, die Leid tragen","Selig sind die Sanftmütigen","Selig sind die Friedensstifter"],rewards:{frieden:2,gerechtigkeit:4,vertrauen:2},card:{type:"Seligpreisungs-Karte",name:"Friedensstifter"},success:"Ihr habt erkannt: Die Seligpreisungen beginnen mit Zuspruch und führen zu einer neuen Sicht auf Gerechtigkeit.",hint:"Schaut im Bibeltext auf die Reihenfolge und die Schlüsselworte."},
  {id:"selig-2",sector:"berg",type:"cards",difficulty:2,title:"Seligpreisungs-Karten deuten",story:"Drei Karten zeigen Haltungen der Bergpredigt. Nicht jede Deutung trifft den Text.",source:"Mt 5,6-9: Gerechtigkeit, Barmherzigkeit und Frieden gehören zusammen.",question:"Ordnet jeder Karte die tragfähige Deutung zu.",items:[["Hunger nach Gerechtigkeit","nicht nur Wunsch nach Vorteil, sondern Sehnsucht nach Gottes gerechter Wirklichkeit"],["Barmherzigkeit","Not sehen und verantwortlich handeln"],["Frieden stiften","Konflikte aktiv klären und Beziehungen heilen"]],correct:["nicht nur Wunsch nach Vorteil, sondern Sehnsucht nach Gottes gerechter Wirklichkeit","Not sehen und verantwortlich handeln","Konflikte aktiv klären und Beziehungen heilen"],rewards:{frieden:4,gerechtigkeit:4,vertrauen:1},card:{type:"Tugend-Karte",name:"Barmherzigkeit"},success:"Stark: Ihr lest die Karten nicht als nette Sprüche, sondern als Zumutung und Zuspruch.",hint:"Achtet darauf, ob eine Deutung nur Stimmung beschreibt oder wirklich Handlung eröffnet."},
  {id:"selig-3",sector:"berg",type:"case",difficulty:3,title:"Fallentscheidung am Berg",story:"Eine Klasse überlegt, ob sie eine ausgeschlossene Person unterstützt, obwohl das Ärger geben könnte.",source:"Mt 5,9-10: Selig sind, die Frieden stiften; selig sind, die um der Gerechtigkeit willen verfolgt werden.",question:"Welche Entscheidung passt am besten zu den Seligpreisungen?",answers:["Wir halten uns heraus, damit niemand etwas gegen uns hat.","Wir helfen heimlich, aber sagen öffentlich nichts.","Wir suchen Schutz, sprechen Unrecht an und versuchen eine faire Klärung.","Wir beschämen die Gegenseite öffentlich."],correct:2,rewards:{frieden:5,gerechtigkeit:6,vertrauen:2},card:{type:"Seligpreisungs-Karte",name:"Gerechtigkeit wagen"},success:"Genau: Frieden stiften heißt nicht ausweichen, sondern gerecht und schützend handeln.",hint:"Frieden und Gerechtigkeit stehen im Text nebeneinander."},
  {id:"anti-1",sector:"tiberias",type:"match",difficulty:1,title:"Ihr habt gehört / Ich aber sage",story:"Die Antithesen bestehen aus alter Formulierung und Jesu Zuspitzung.",source:"Mt 5,21-48: Jesus spricht über Töten/Zorn, Ehebruch/Blick, Schwören/Wahrhaftigkeit, Vergeltung/Feindesliebe.",question:"Ordnet Jesu Zuspitzung dem Thema zu.",items:[["Töten","Schon Zorn und Beschimpfung zerstören Gemeinschaft"],["Schwören","Euer Ja sei ein Ja, euer Nein ein Nein"],["Vergeltung","Nicht zurückschlagen, sondern die Spirale unterbrechen"],["Feindesliebe","Auch für Gegner beten und Vergeltung überwinden"]],correct:["Schon Zorn und Beschimpfung zerstören Gemeinschaft","Euer Ja sei ein Ja, euer Nein ein Nein","Nicht zurückschlagen, sondern die Spirale unterbrechen","Auch für Gegner beten und Vergeltung überwinden"],rewards:{frieden:5,gerechtigkeit:3,vertrauen:2},card:{type:"Tugend-Karte",name:"Wahrhaftigkeit"},success:"Ihr erkennt die Struktur: Jesus fragt nach der Wurzel des Handelns.",hint:"Sucht im Bibeltext jeweils den Satz nach 'Ich aber sage euch'."},
  {id:"anti-2",sector:"tiberias",type:"quest",difficulty:2,title:"Moralquest: Streit im Tor",story:"Zwei Gruppen beleidigen sich. Eine Seite will zurückschlagen.",source:"Mt 5,22-24 und Mt 5,39: Versöhnung suchen; die Logik der Vergeltung unterbrechen.",question:"Wählt die drei Schritte, die der Antithesen-Logik am ehesten entsprechen.",answers:["Beleidigung sofort mit Beleidigung beantworten","Gefahr stoppen und Abstand schaffen","Unrecht benennen, ohne zu beschämen","Gespräch und Wiedergutmachung ermöglichen","Gerüchte sammeln, um stärker zu wirken"],correct:[1,2,3],rewards:{frieden:6,gerechtigkeit:5,vertrauen:1},card:{type:"Tugend-Karte",name:"Versöhnung"},success:"Richtig: Schutz, Wahrheit und Versöhnung gehören zusammen.",hint:"Feindesliebe heißt nicht Schutzlosigkeit; Vergeltung ist trotzdem keine Lösung."},
  {id:"anti-3",sector:"tiberias",type:"conflict",difficulty:3,title:"Konfliktkarten: Feindesliebe",story:"Ein Gegner hat euch unfair behandelt. Eure Entscheidung verändert die Moralpunkte.",source:"Mt 5,44: Liebt eure Feinde und bittet für die, die euch verfolgen.",question:"Welche Karte ist theologisch am tragfähigsten?",answers:["Rachekarte: Wir zahlen es mit gleicher Härte zurück.","Schweigenkarte: Wir tun so, als sei nichts passiert.","Friedenskarte: Wir schützen Betroffene, benennen Unrecht und lassen einen Weg zur Umkehr offen.","Siegerkarte: Wir blamieren die andere Seite, damit sie lernt."],correct:2,rewards:{frieden:8,gerechtigkeit:6,vertrauen:3},card:{type:"Tugend-Karte",name:"Feindesliebe ohne Naivität"},success:"Das ist die schwere Mitte: keine Vergeltung, keine Verharmlosung.",hint:"Prüft, welche Karte gleichzeitig Frieden und Gerechtigkeit stärkt."},
  {id:"vater-1",sector:"see",type:"puzzle",difficulty:1,title:"Vaterunser-Puzzle",story:"Die Bitten des Vaterunsers liegen als Puzzleteile vor.",source:"Mt 6,9-13: Geheiligt werde dein Name. Dein Reich komme. Dein Wille geschehe. Unser tägliches Brot gib uns heute. Vergib uns unsere Schuld. Führe uns nicht in Versuchung. Erlöse uns von dem Bösen.",question:"Bringt vier zentrale Bitten in eine sinnvolle Reihenfolge.",items:["Geheiligt werde dein Name","Dein Reich komme","Unser tägliches Brot gib uns heute","Vergib uns unsere Schuld"],correct:["Geheiligt werde dein Name","Dein Reich komme","Unser tägliches Brot gib uns heute","Vergib uns unsere Schuld"],rewards:{frieden:1,gerechtigkeit:2,vertrauen:6},card:{type:"Gleichnis-Karte",name:"Gebet als Ausrichtung"},success:"Gut gepuzzelt: Das Gebet beginnt bei Gott und führt dann in menschliche Bedürfnisse.",hint:"Schaut im Bibeltext: Zuerst Gottes Name/Reich/Wille, dann Brot und Schuld."},
  {id:"vater-2",sector:"see",type:"compass",difficulty:2,title:"Bitten-Kompass",story:"Jede Bitte hat eine Richtung: Vertrauen, Versorgung, Vergebung oder Bewahrung.",source:"Mt 6,9-13 verbindet Gottes Reich, tägliches Brot, Schuldvergebung und Rettung.",question:"Ordnet Bitte und Bedeutung zu.",items:[["Dein Reich komme","Hoffnung auf Gottes gerechte Wirklichkeit"],["Unser tägliches Brot gib uns heute","Vertrauen auf das Notwendige für alle"],["Vergib uns unsere Schuld","Versöhnung empfangen und weitergeben"],["Erlöse uns von dem Bösen","Bitte um Bewahrung vor zerstörerischer Macht"]],correct:["Hoffnung auf Gottes gerechte Wirklichkeit","Vertrauen auf das Notwendige für alle","Versöhnung empfangen und weitergeben","Bitte um Bewahrung vor zerstörerischer Macht"],rewards:{frieden:3,gerechtigkeit:4,vertrauen:6},card:{type:"Tugend-Karte",name:"Vertrauen"},success:"Ihr habt gesehen: Das Vaterunser ist kein Rückzug aus der Welt.",hint:"Achtet auf die Verben: kommen, geben, vergeben, erlösen."},
  {id:"vater-3",sector:"see",type:"trust",difficulty:3,title:"Vertrauensquest",story:"Eine Gruppe hat Angst, zu kurz zu kommen, wenn sie teilt.",source:"Mt 6,11-12: Unser tägliches Brot gib uns heute; vergib uns unsere Schuld, wie auch wir vergeben.",question:"Welche Entscheidung passt am besten zum Vaterunser?",answers:["Wir sichern zuerst alles für uns, Vertrauen ist Privatsache.","Wir teilen planlos alles und kümmern uns nicht um morgen.","Wir prüfen den Bedarf, teilen fair und halten Vergebung als nächsten Schritt offen.","Wir geben nur denen etwas, die uns später helfen können."],correct:2,rewards:{frieden:5,gerechtigkeit:5,vertrauen:7},card:{type:"Tugend-Karte",name:"Geteiltes Brot"},success:"Tragfähig: Vertrauen wird konkret, ohne Verantwortung aufzugeben.",hint:"Brot und Schuld stehen im Gebet nebeneinander: Versorgung und Beziehung."},
  {id:"gold-1",sector:"nazareth",type:"decode",difficulty:1,title:"Goldene Regel entschlüsseln",story:"Ein verschlüsselter Satz bündelt den Lernweg.",source:"Mt 7,12: Alles, was ihr wollt, dass euch die Leute tun, das tut ihr ihnen auch.",question:"Welche Entschlüsselung trifft die Goldene Regel?",answers:["Handle so, dass du immer gewinnst.","Warte ab, bis andere den ersten Schritt machen.","Nimm die Perspektive der anderen ein und handle entsprechend.","Behandle alle exakt gleich, egal was sie brauchen."],correct:2,rewards:{frieden:3,gerechtigkeit:5,vertrauen:2},card:{type:"Tugend-Karte",name:"Perspektivwechsel"},success:"Richtig: Die Goldene Regel ist aktiver Perspektivwechsel.",hint:"Achtet auf 'was ihr wollt' und 'das tut ihr ihnen auch'."},
  {id:"gold-2",sector:"nazareth",type:"logic",difficulty:2,title:"Haus auf Fels und Sand",story:"Zwei Bauleute hören dieselben Worte. Nur einer handelt danach.",source:"Mt 7,24-27: Wer Jesu Worte hört und tut, baut auf Fels; wer hört und nicht tut, baut auf Sand.",question:"Ordnet die Logik des Gleichnisses.",items:["Jesu Worte hören","Jesu Worte tun","Haus auf Fels bauen","Sturm besteht"],correct:["Jesu Worte hören","Jesu Worte tun","Haus auf Fels bauen","Sturm besteht"],rewards:{frieden:2,gerechtigkeit:4,vertrauen:6},card:{type:"Gleichnis-Karte",name:"Haus auf Fels"},success:"Genau: Nicht das Hören allein trägt, sondern das Tun.",hint:"Im Gleichnis unterscheiden sich die Bauleute nicht beim Hören, sondern beim Tun."},
  {id:"gold-3",sector:"nazareth",type:"rpg",difficulty:3,title:"Finalquest: Felsbauer",story:"Ihr entscheidet über einen Streit, knappe Ressourcen und eine Person, die ausgeschlossen wurde.",source:"Mt 7,12 und Mt 7,24: Perspektivwechsel tun; auf Fels bauen.",question:"Welche Entscheidung macht euch zu Felsbauern?",answers:["Wir wählen die bequemste Lösung für unsere Gruppe.","Wir hören alle Seiten, prüfen Bedürfnisse, schützen Schwächere und treffen eine überprüfbare Vereinbarung.","Wir stimmen schnell ab, damit Ruhe ist.","Wir helfen nur denen, die vorher auf unserer Seite waren."],correct:1,rewards:{frieden:8,gerechtigkeit:8,vertrauen:6},card:{type:"Gleichnis-Karte",name:"Felsbauer"},success:"Ihr habt die Bergpredigt gebündelt: hören, prüfen, handeln.",hint:"Felsbau bedeutet: Die Goldene Regel wird getan, nicht nur erklärt."}
];
sortTasksByLearningPath(TASKS);
const db=createDb(),STATE_KEY="bergpredigt-tablet-state-v5";let sessionId=getActiveSession()||randomSession(),groupId="",taskIndex=0,solved=new Set(),completedGames=new Set(),attempts=0,locked=false,excluded=false,liveChannel=null,sessionRows=[],sessionCompletion=new Map(),groupTarget=4,lastPromptSeen="",selectedAvatar=AVATARS[0].id,finaleSeen=false,feedbackSeen=new Set(),localScores={frieden:0,gerechtigkeit:0,vertrauen:0},localCards=[];setActiveSession(sessionId);
function sanitizeGroupId(value){return value.trim().toLowerCase().replace(/[^a-z0-9_-]/g,"").slice(0,24)}
function stateId(){return`${STATE_KEY}:${sessionId}:${groupId}`}
function saveState(){if(groupId)localStorage.setItem(stateId(),JSON.stringify({taskIndex,solved:[...solved],completedGames:[...completedGames],scores:localScores,cards:localCards,avatar:selectedAvatar}))}
function restoreState(){try{const saved=JSON.parse(localStorage.getItem(stateId())||"{}");taskIndex=Math.min(Number(saved.taskIndex)||0,TASKS.length);solved=new Set(saved.solved||[]);completedGames=new Set(saved.completedGames||[]);localScores={frieden:0,gerechtigkeit:0,vertrauen:0,...(saved.scores||{})};localCards=saved.cards||[];selectedAvatar=saved.avatar||selectedAvatar}catch{taskIndex=0;solved=new Set();completedGames=new Set();localScores={frieden:0,gerechtigkeit:0,vertrauen:0};localCards=[]}}
function saveAvatarState(){if(groupId){const saved=JSON.parse(localStorage.getItem(stateId())||"{}");localStorage.setItem(stateId(),JSON.stringify({...saved,avatar:selectedAvatar}))}}
function totalScore(){return VALUE_KEYS.reduce((sum,key)=>sum+(localScores[key]||0),0)}
function renderHud(){const hud=document.getElementById("gameHud");if(!hud)return;const rank=rankForScore(totalScore());hud.innerHTML=`<div class="rank-card"><b>${rank.name}</b><span>${totalScore()} Punkte</span></div>${VALUE_KEYS.map(key=>`<div class="value-chip"><b>${VALUE_LABELS[key]}</b><span>${localScores[key]||0}</span></div>`).join("")}<div class="card-chip"><b>Karten</b><span>${localCards.length}</span></div>`}
function selectAvatar(id){selectedAvatar=AVATARS.some(avatar=>avatar.id===id)?id:AVATARS[0].id;document.querySelectorAll("[data-avatar-choice]").forEach(button=>button.classList.toggle("selected",button.dataset.avatarChoice===selectedAvatar))}
function renderAvatarPicker(){document.getElementById("avatarPicker").innerHTML=AVATARS.map(avatar=>`<button class="avatar-choice ${avatar.id===selectedAvatar?"selected":""}" type="button" data-avatar-choice="${avatar.id}" aria-pressed="${avatar.id===selectedAvatar}"><span class="avatar-token" style="--avatar-pos:${avatar.pos}"></span><b>${avatar.name}</b></button>`).join("");document.querySelectorAll("[data-avatar-choice]").forEach(button=>button.addEventListener("click",()=>{selectAvatar(button.dataset.avatarChoice);document.querySelectorAll("[data-avatar-choice]").forEach(item=>item.setAttribute("aria-pressed",String(item.dataset.avatarChoice===selectedAvatar)))}))}
function stationPart(index){const sector=TASKS[index]?.sector;if(!sector)return{part:0,total:0};const tasks=TASKS.filter(task=>task.sector===sector),part=TASKS.slice(0,index+1).filter(task=>task.sector===sector).length;return{part,total:tasks.length}}
function renderFogMap(){const current=TASKS[taskIndex]?.sector,isCoop=activeWorkMode(sessionRows)==="cooperative";document.getElementById("tabletFogMap").innerHTML=SECTORS.map((sector,i)=>{const state=sessionCompletion.get(sector.id)||{count:0,required:isCoop?groupTarget:1,complete:false},isOwnDone=solved.has(sector.id),isCurrent=sector.id===current,label=state.complete||isOwnDone||isCurrent?sector.name:`Modul ${i+1}`,detail=state.complete?"gemeinsam erschlossen":isCoop?`${state.count}/${state.required} Gruppenbeiträge`:isCurrent?"jetzt spielen":"noch offen";return`<div class="${state.complete||isOwnDone?"done":""} ${isCurrent?"current":""}"><img src="${sector.art}" alt=""><b>${label}</b><span>${detail}</span></div>`}).join("")}
function showPromptPopup(prompt){if(!prompt||prompt===lastPromptSeen)return;lastPromptSeen=prompt;document.getElementById("promptPopupText").textContent=prompt;document.getElementById("promptPopup").classList.remove("hidden")}
function renderProgress(){document.getElementById("sessionLabel").textContent=sessionId;document.getElementById("tabletProgress").innerHTML=SECTORS.map(sector=>`<span class="${solved.has(sector.id)?"done":""}" title="${sector.name}"></span>`).join("");renderFogMap();renderHud();document.getElementById("tabletLock").classList.toggle("hidden",!locked);document.getElementById("tabletExcluded").classList.toggle("hidden",!excluded);const mode=WORK_MODES[activeWorkMode(sessionRows)];document.getElementById("phaseBanner").textContent=`Phase: ${activePhase(sessionRows)} · Modus: ${mode.name}`;const prompt=activePrompt(sessionRows),box=document.getElementById("livePrompt");box.classList.toggle("hidden",!prompt);box.innerHTML=prompt?`<b>Live-Auftrag der Lehrkraft</b><span>${escapeHtml(prompt)}</span>`:"";showPromptPopup(prompt);if(finaleRequested(sessionRows)&&!finaleSeen){finaleSeen=true;document.getElementById("finalePrompt").classList.remove("hidden")}}
function biblePanelMarkup(sectorId){const panel=BIBLE_PANELS[sectorId];return panel?`<details class="bible-panel" open><summary>Bibeltext-Hilfe (${escapeHtml(panel.reference)})</summary><p>${escapeHtml(panel.text)}</p><small>Alle Spiele dieses Moduls sind nur mit diesem Textbezug lösbar.</small></details>`:""}
function rewardMarkup(task){return`<div class="reward-row">${VALUE_KEYS.map(key=>`<span>${VALUE_LABELS[key]} +${task.rewards?.[key]||0}</span>`).join("")}<span>${escapeHtml(task.card?.type||"Karte")}: ${escapeHtml(task.card?.name||"-")}</span></div>`}
function productMarkup(task,next){return(!next||next.sector!==task.sector)?`<section class="product-card"><h3>Anonymer Merksatz für die Tafel</h3><p>Formuliert einen Satz, den ihr aus diesem Modul ins Plenum mitnehmt.</p><textarea id="productText" maxlength="220" placeholder="Unser Merksatz ..."></textarea></section>`:""}
function debateMarkup(){return`<section class="debate-card"><p class="comic-kicker">Debatten-Finale</p><h2>${escapeHtml(DEBATE_FINALE.question)}</h2><p>Wählt Argumentkarten für eine Position. Eure Auswahl erscheint anonym in der Plenumsarena.</p><div class="debate-columns">${DEBATE_FINALE.positions.map((position,index)=>`<div><h3>Position ${index+1}</h3><p>${escapeHtml(position)}</p><div class="debate-drop" data-debate-slot="${index}"></div></div>`).join("")}</div><div class="debate-arguments">${DEBATE_FINALE.arguments.map(argument=>`<button class="argument-card" type="button">${escapeHtml(argument)}</button>`).join("")}</div><button class="comic-button" id="sendDebate" type="button">Argumente an Tafel senden</button></section>`}
function bindDebate(){document.querySelectorAll(".argument-card").forEach(button=>button.addEventListener("click",()=>{const side=button.dataset.side==="0"?"1":"0";button.dataset.side=side;document.querySelector(`[data-debate-slot="${side}"]`).append(button)}));document.getElementById("sendDebate")?.addEventListener("click",sendDebate)}
async function sendDebate(){const cards=[...document.querySelectorAll(".debate-drop .argument-card")].slice(0,4);for(const card of cards){await markDone(db,{session_id:sessionId,gruppen_id:groupId,sektor:"control",status:"erledigt",event_type:"prompt",payload:`debate:${card.dataset.side||0}:${card.textContent.slice(0,180)}`})}document.getElementById("sendDebate").textContent="Gesendet"}
function showFeedbackCard(sectorId){if(feedbackSeen.has(sectorId))return;feedbackSeen.add(sectorId);document.getElementById("feedbackPopupText").textContent=feedbackFor(sectorId,sessionRows);document.getElementById("feedbackPopup").classList.remove("hidden")}
async function submitMiss(task){try{await markDone(db,{session_id:sessionId,gruppen_id:groupId,sektor:"control",status:"erledigt",event_type:"prompt",payload:`miss:${taskIndex}:${task.type}:${task.sector}`})}catch(error){console.error(error)}}
async function submitProduct(sectorId){const text=document.getElementById("productText")?.value.trim().replace(/\s+/g," ").slice(0,220);if(!text)return;try{await markDone(db,{session_id:sessionId,gruppen_id:groupId,sektor:"control",status:"erledigt",event_type:"prompt",payload:`product:${sectorId}:${text}`})}catch(error){console.error(error)}}
async function awardTask(task){if(completedGames.has(task.id))return;completedGames.add(task.id);VALUE_KEYS.forEach(key=>localScores[key]=(localScores[key]||0)+(task.rewards?.[key]||0));if(task.card)localCards.push(task.card);saveState();try{await markDone(db,{session_id:sessionId,gruppen_id:groupId,sektor:"control",status:"erledigt",event_type:"prompt",payload:`score:${task.id}:${VALUE_KEYS.map(key=>`${key}=${task.rewards?.[key]||0}`).join(",")}`});if(task.card)await markDone(db,{session_id:sessionId,gruppen_id:groupId,sektor:"control",status:"erledigt",event_type:"prompt",payload:`card:${task.card.type}:${task.card.name}`})}catch(error){console.error(error)}renderHud()}
function choiceMarkup(task,multiple=false){return task.answers.map((answer,i)=>`<label class="answer"><input type="${multiple?"checkbox":"radio"}" name="answer" value="${i}"><span>${answer}</span></label>`).join("")}
function selectMarkup(name,items,categories){return items.map(([statement],i)=>`<label class="select-answer"><span>${statement}</span><select name="${name}"><option value="">Bitte zuordnen</option>${categories.map(category=>`<option>${category}</option>`).join("")}</select></label>`).join("")}
function answerMarkup(task){if(["case","conflict","decode","rpg","trust"].includes(task.type))return choiceMarkup(task);if(["quest"].includes(task.type))return choiceMarkup(task,true);if(["sort","puzzle","logic"].includes(task.type))return task.correct.map((_,i)=>`<label class="select-answer"><b>${i+1}.</b><select name="order"><option value="">Karte auswählen</option>${task.items.map(item=>`<option>${item}</option>`).join("")}</select></label>`).join("");if(["match","cards","compass"].includes(task.type))return selectMarkup(task.type,task.items,task.correct);return choiceMarkup(task)}
function values(name){return[...document.querySelectorAll(`[name="${name}"]`)].map(input=>input.value)}
function isCorrect(task){if(["case","conflict","decode","rpg","trust"].includes(task.type))return Number(document.querySelector('input[name="answer"]:checked')?.value)===task.correct;if(task.type==="quest"){const checked=[...document.querySelectorAll('input[name="answer"]:checked')].map(input=>Number(input.value));return JSON.stringify(checked)===JSON.stringify(task.correct)}if(["sort","puzzle","logic"].includes(task.type))return values("order").every((value,i)=>value===task.correct[i]);if(["match","cards","compass"].includes(task.type))return values(task.type).every((value,i)=>value===task.correct[i]);return false}
function renderTask(){attempts=0;renderProgress();const card=document.getElementById("taskCard");if(taskIndex>=TASKS.length){card.className="task-card final-card";card.innerHTML=finaleRequested(sessionRows)?debateMarkup():"<p class='comic-kicker'>Mission geschafft</p><h2>Ihr seid bereit für das Finale!</h2><p>Wartet auf die Plenumsarena der Lehrkraft.</p>";bindDebate();return}const task=TASKS[taskIndex],next=TASKS[taskIndex+1],sector=SECTORS.find(s=>s.id===task.sector),module=moduleFor(task.sector,sessionRows),part=stationPart(taskIndex),isCoop=activeWorkMode(sessionRows)==="cooperative",state=sessionCompletion.get(sector.id)||{count:0,required:isCoop?groupTarget:1};card.className="task-card";card.innerHTML=`<div class="station-header"><span class="station-number">${sector.name} · Spiel ${part.part}/${part.total} · Schwierigkeit ${task.difficulty}</span><b>${taskSkillLabel(task)}</b></div><p class="coop-note">${isCoop?`${state.count}/${state.required} aktive Gruppen haben dieses Modul gesichert.`:"Euer Modulabschluss kann die Tafel öffnen."}</p><section class="module-context"><p class="comic-kicker">${escapeHtml(module.title)}</p><p>${escapeHtml(module.narrative)}</p><small><b>Rangziel:</b> Suchender → Felsbauer</small></section>${biblePanelMarkup(task.sector)}${rewardMarkup(task)}<h2>${task.title}</h2><p class="story-bubble">${task.story}</p><p class="source">${task.source}</p><h3>${task.question}</h3><div class="answers">${answerMarkup(task)}</div>${productMarkup(task,next)}<div class="feedback hidden" id="feedback" aria-live="polite"></div><div class="task-actions"><button class="comic-button" id="checkAnswer" type="button">Spiel prüfen</button><button class="comic-button next-task hidden" id="nextTask" type="button">Weiter →</button></div>`;document.getElementById("checkAnswer").addEventListener("click",checkAnswer);document.getElementById("nextTask").addEventListener("click",advance)}
async function checkAnswer(){if(locked||excluded)return;const task=TASKS[taskIndex],feedback=document.getElementById("feedback");if(!isCorrect(task)){attempts++;submitMiss(task);feedback.className="feedback bad";feedback.textContent=attempts>1?`Noch nicht tragfähig. Hinweis: ${task.hint}`:"Noch nicht. Nutzt den Bibeltext genau und besprecht eure Wahl.";return}feedback.className="feedback good";feedback.textContent=`✓ ${task.success}`;document.querySelectorAll(".task-card input,.task-card select").forEach(input=>input.disabled=true);document.getElementById("checkAnswer").classList.add("hidden");document.getElementById("nextTask").classList.remove("hidden");await awardTask(task)}
async function advance(){if(locked||excluded)return;const current=TASKS[taskIndex],next=TASKS[taskIndex+1],stationComplete=!next||next.sector!==current.sector,button=document.getElementById("nextTask");button.disabled=true;try{if(stationComplete&&!solved.has(current.sector)){await submitProduct(current.sector);await markDone(db,{session_id:sessionId,gruppen_id:groupId,sektor:current.sector,status:"erledigt"});solved.add(current.sector)}taskIndex++;saveState();renderTask();if(stationComplete)showFeedbackCard(current.sector)}catch(error){console.error(error);button.disabled=false;document.getElementById("feedback").className="feedback bad";document.getElementById("feedback").textContent="Das Spiel ist gelöst, aber die Übertragung hat nicht geklappt. Bitte versucht es erneut."}}
async function refreshControl(){try{sessionRows=await readProgress(db,sessionId);locked=isSessionLocked(sessionRows);excluded=groupId?isGroupExcluded(sessionRows,groupId):false;groupTarget=effectiveGroupTargetFromRows(sessionRows);sessionCompletion=sectorCompletion(sessionRows);renderProgress();if(taskIndex>=TASKS.length)renderTask()}catch(error){console.error(error)}}
function subscribeControl(){if(!db)return;if(liveChannel)db.removeChannel(liveChannel);liveChannel=db.channel(`tablet-control-${sessionId}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"fortschritt",filter:`session_id=eq.${sessionId}`},()=>refreshControl()).subscribe()}
document.getElementById("groupForm").addEventListener("submit",async event=>{event.preventDefault();groupId=sanitizeGroupId(document.getElementById("groupInput").value);const chosenAvatar=selectedAvatar;if(groupId.length<2)return;restoreState();selectedAvatar=chosenAvatar;saveAvatarState();try{await markDone(db,{session_id:sessionId,gruppen_id:groupId,sektor:"control",status:"erledigt",event_type:"manual",payload:`avatar:${selectedAvatar}`})}catch(error){console.error(error)}await refreshControl();subscribeControl();document.getElementById("groupSetup").classList.add("hidden");document.getElementById("missionArea").classList.remove("hidden");document.getElementById("groupLabel").innerHTML=`<span class="avatar-token tiny" style="--avatar-pos:${avatarById(selectedAvatar).pos}"></span> Gruppe: ${escapeHtml(groupId)}`;renderTask()});
document.getElementById("changeGroup").addEventListener("click",()=>{groupId="";taskIndex=0;solved=new Set();completedGames=new Set();localScores={frieden:0,gerechtigkeit:0,vertrauen:0};localCards=[];document.getElementById("groupSetup").classList.remove("hidden");document.getElementById("missionArea").classList.add("hidden");document.getElementById("groupInput").focus()});
document.getElementById("closePromptPopup").addEventListener("click",()=>document.getElementById("promptPopup").classList.add("hidden"));
document.getElementById("closeFinalePrompt").addEventListener("click",()=>document.getElementById("finalePrompt").classList.add("hidden"));
document.getElementById("closeFeedbackPopup").addEventListener("click",()=>document.getElementById("feedbackPopup").classList.add("hidden"));
setConnectionStatus(db?"Live verbunden":"Demo-Modus",Boolean(db));renderAvatarPicker();renderProgress();
