const db=createDb();let rows=[],doneIds=new Set(),completion=new Map(),sessionId=getActiveSession()||randomSession(),finale=false,locked=false,groupTarget=1,refreshing=false,finaleDismissed=false;
const AVATAR_POINTS=[[51,64],[42,60],[60,40],[80,61],[62,82]];
setActiveSession(sessionId);document.getElementById("sessionLabel").textContent=sessionId;
function celebrate(sector){const burst=document.getElementById("unlockBurst"),map=document.querySelector(".map-card");burst.innerHTML=`<i>✦</i><i>•</i><b>PLING!</b><span>${sector.name} ist freigeschaltet.</span><i>✦</i><i>•</i>`;burst.classList.remove("hidden");map.classList.add("map-celebrate");setTimeout(()=>{burst.classList.add("hidden");map.classList.remove("map-celebrate")},1800)}
function showFinale(force=false){if(finaleDismissed&&!force)return;document.getElementById("boardFinale").classList.remove("hidden");document.getElementById("reopenFinale").classList.add("hidden")}
function groupProgressMap(){const groups=new Map(),excluded=excludedGroups(rows);groupAvatarsFromRows(rows).forEach((avatar,group)=>groups.set(group,new Set()));rows.filter(row=>row.status==="erledigt"&&row.sektor!=="control"&&row.sektor!=="finale"&&row.gruppen_id!=="lehrkraft"&&!excluded.has(row.gruppen_id)).forEach(row=>{if(!groups.has(row.gruppen_id))groups.set(row.gruppen_id,new Set());groups.get(row.gruppen_id).add(row.sektor)});return groups}
function renderGroupAvatars(){const layer=document.getElementById("groupAvatarLayer"),avatars=groupAvatarsFromRows(rows),groups=[...groupProgressMap()].sort(([a],[b])=>a.localeCompare(b));layer.innerHTML=groups.map(([group,sectors],index)=>{const furthest=SECTORS.reduce((highest,sector,sectorIndex)=>sectors.has(sector.id)?sectorIndex:highest,-1)+1,point=AVATAR_POINTS[Math.min(furthest,AVATAR_POINTS.length-1)],avatar=avatarById(avatars.get(group)),offset=(index%5-2)*1.4;return `<div class="group-map-avatar" style="--x:${point[0]+offset}%;--y:${point[1]+Math.floor(index/5)*3}%;--avatar-pos:${avatar.pos}" title="${escapeHtml(group)}"><span class="avatar-token"></span><b>${escapeHtml(group)}</b></div>`}).join("")}
function renderAvatarProgress(){const list=document.getElementById("avatarProgressList"),avatars=groupAvatarsFromRows(rows),groups=[...groupProgressMap()].sort(([a],[b])=>a.localeCompare(b));list.innerHTML=groups.length?groups.map(([group,sectors])=>{const count=SECTORS.filter(sector=>sectors.has(sector.id)).length,current=SECTORS[Math.min(count,SECTORS.length-1)],avatar=avatarById(avatars.get(group));return `<div class="avatar-progress-card"><span class="avatar-token tiny" style="--avatar-pos:${avatar.pos}"></span><small><b>${escapeHtml(group)}</b><span>${count}/${SECTORS.length} · ${count===SECTORS.length?"bereit fürs Finale":current.name}</span></small><i style="width:${count/SECTORS.length*100}%"></i></div>`}).join(""):"<p class='privacy-note'>Noch keine Gruppenavatare gewählt.</p>"}
function renderClassCompass(){
  const target=document.getElementById("classCompass");
  if(!target)return;
  const totals=classValueTotals(rows),threshold=compassThreshold(rows),max=Math.max(threshold,...VALUE_KEYS.map(key=>totals[key])),sorted=VALUE_KEYS.slice().sort((a,b)=>totals[b]-totals[a]),strong=sorted[0],weak=compassWeakValues(rows);
  target.innerHTML=`<div class="class-compass">${VALUE_KEYS.map(key=>`<div class="compass-row ${key===strong?"strong":""} ${weak.includes(key)?"weak":""}"><b>${VALUE_LABELS[key]}</b><span>${totals[key]} / ${threshold}</span><i><em style="width:${Math.min(100,totals[key]/max*100)}%"></em></i></div>`).join("")}</div><div class="compass-insight"><b>Funktion:</b> Das Finale öffnet erst, wenn alle drei Werte den Zielwert erreichen. ${weak.length?`Nacharbeit: ${weak.map(key=>VALUE_LABELS[key]).join(", ")}.`:"Der Klassen-Kompass ist tragfähig."}</div><p class="privacy-note">Kompasspunkte sind keine Note, sondern ein funktionaler Plenumsauftrag.</p>`;
}
function renderCardWall(){
  const target=document.getElementById("cardWall");
  if(!target)return;
  const cards=cardRows(rows),grouped=[...cards.reduce((map,card)=>{const key=`${card.type}:${card.name}`;if(!map.has(key))map.set(key,{...card,count:0,groups:new Set()});const item=map.get(key);item.count++;item.groups.add(card.group);return map},new Map()).values()].sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name));
  const icon=type=>type.startsWith("Selig")?"S":type.startsWith("Gleichnis")?"G":"T";
  target.innerHTML=grouped.length?`<div class="card-wall">${grouped.slice(0,18).map(card=>`<article class="collection-card"><i>${icon(card.type)}</i><b>${escapeHtml(card.name)}</b><small>${escapeHtml(card.type)} · ${card.count}x</small><em>${card.groups.size} Gruppen können belegen</em></article>`).join("")}</div><p class="privacy-note">${cards.length} Karten gesammelt · ${grouped.length} verschiedene Karten. Funktion: Karten liefern Bibelbelege für Argumente.</p>`:"<p class='privacy-note'>Noch keine Sammelkarten freigeschaltet.</p>";
}
function renderPlenumArena(){
  const target=document.getElementById("plenumArena");
  if(!target)return;
  const products=productRows(rows).slice(-5).reverse(),diagnostics=diagnosticSummary(rows).slice(0,3),misses=diagnosticRows(rows).slice(-6).reverse(),debates=debateRows(rows);
  const debateColumns=DEBATE_FINALE.positions.map((position,index)=>{
    const items=debates.filter(item=>item.side===index).slice(-5).reverse();
    return `<div><h3>Position ${index+1}</h3><p>${escapeHtml(position)}</p>${items.length?items.map(item=>`<span class="argument-pill">${escapeHtml(item.text)}</span>`).join(""):"<small>Noch keine Argumentkarten.</small>"}</div>`;
  }).join("");
  const html=`<p class="final-question compact">${escapeHtml(DEBATE_FINALE.question)}</p><div class="plenum-status"><b>${debates.length}</b><span>Argumentkarten eingegangen</span><b>${products.length}</b><span>Merksätze sichtbar</span></div><div class="plenum-columns">${debateColumns}</div><h3>Merksätze</h3><div class="product-ticker">${products.length?products.map(item=>`<span>${escapeHtml(item.text)}</span>`).join(""):"<small>Noch keine Merksätze eingegangen.</small>"}</div><h3>Gemeinsam genauer hinschauen</h3><div class="diagnostic-ticker">${diagnostics.length?diagnostics.map(item=>{const sector=SECTORS.find(s=>s.id===item.sector);return`<span>${escapeHtml(sector?.name||item.sector)}: ${item.count} Stolperstellen</span>`}).join(""):"<small>Keine auffälligen Stolperstellen.</small>"}</div><div class="miss-log">${misses.length?misses.map(item=>{const sector=SECTORS.find(s=>s.id===item.sector);return`<small>${escapeHtml(sector?.name||item.sector)} · ${escapeHtml(item.type)} · ${escapeHtml(item.group)}</small>`}).join(""):""}</div>`;
  target.innerHTML=html;
  const finale=document.getElementById("finaleLiveArena");if(finale)finale.innerHTML=html;
}
function renderBoard(){const focus=activeFocus(rows);document.querySelectorAll("[data-sector]").forEach(node=>{node.classList.toggle("done",doneIds.has(node.dataset.sector));node.classList.toggle("focus",focus===node.dataset.sector)});document.getElementById("boardLock").classList.toggle("hidden",!locked);document.getElementById("groupTargetLabel").textContent=`${WORK_MODES[activeWorkMode(rows)].name} · ${groupTarget} ${groupTarget===1?"Gruppe":"Gruppen"}`;const reached=SECTORS.filter(sector=>doneIds.has(sector.id)).length,finaleAvailable=reached===SECTORS.length||finale;document.getElementById("expeditionRoute").style.strokeDashoffset=100-reached/SECTORS.length*100;document.getElementById("doneCount").textContent=reached;document.getElementById("progressBar").style.width=`${reached/SECTORS.length*100}%`;document.getElementById("sectorList").innerHTML=SECTORS.map(s=>{const state=completion.get(s.id)||{count:0,required:1,complete:false};return `<div class="${state.complete?"done":""} ${focus===s.id?"focus":""}"><img src="${s.art}" alt=""><span>${state.complete?"✓":state.count}</span><small><b>${s.name}</b>${focus===s.id?"Tafel-Fokus":state.complete?s.title:`${state.count} / ${state.required} Gruppenbeiträge`}</small></div>`}).join("");renderGroupAvatars();renderAvatarProgress();renderClassCompass();renderCardWall();renderPlenumArena();document.getElementById("reopenFinale").classList.toggle("hidden",!finaleAvailable||!finaleDismissed);if(finaleAvailable)showFinale()}
async function acceptRow(row){if(row.session_id!==sessionId||row.status!=="erledigt")return;if(row.sektor==="finale"){finale=true;finaleDismissed=false;showFinale(true);return}const before=new Set(doneIds);await refresh();const sector=SECTORS.find(s=>s.id===row.sektor);if(sector&&!before.has(sector.id)&&doneIds.has(sector.id))celebrate(sector)}
async function refresh(){if(refreshing)return;refreshing=true;try{rows=await readProgress(db,sessionId);completion=sectorCompletion(rows);doneIds=completedSectorIds(rows);finale=finaleRequested(rows);locked=isSessionLocked(rows);groupTarget=effectiveGroupTargetFromRows(rows);renderBoard()}finally{refreshing=false}}
async function start(){try{await refresh();setInterval(refresh,3000);document.addEventListener("visibilitychange",()=>{if(!document.hidden)refresh()});if(!db){setConnectionStatus("Demo-Modus",false);window.addEventListener("storage",event=>{if(event.key===LOCAL_KEY)refresh()});window.addEventListener("berg-local-progress",event=>acceptRow(event.detail));return}setConnectionStatus("Live verbunden",true);db.channel(`tafel-${sessionId}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"fortschritt",filter:`session_id=eq.${sessionId}`},payload=>acceptRow(payload.new)).subscribe(status=>{if(status==="SUBSCRIBED")setConnectionStatus("Live verbunden",true)})}catch(error){console.error(error);setConnectionStatus("Verbindung prüfen",false)}}
document.getElementById("fullscreenMap").addEventListener("click",async()=>{const board=document.body,button=document.getElementById("fullscreenMap");try{if(document.fullscreenElement){await document.exitFullscreen();button.textContent="Tafel Vollbild"}else{await board.requestFullscreen();button.textContent="Vollbild verlassen"}}catch{board.classList.toggle("board-fullscreen-fallback");button.textContent=board.classList.contains("board-fullscreen-fallback")?"Vollbild verlassen":"Tafel Vollbild"}});
document.addEventListener("fullscreenchange",()=>document.getElementById("fullscreenMap").textContent=document.fullscreenElement?"Vollbild verlassen":"Tafel Vollbild");
document.getElementById("closeFinale").addEventListener("click",()=>{finaleDismissed=true;document.getElementById("boardFinale").classList.add("hidden");document.getElementById("reopenFinale").classList.remove("hidden")});
document.getElementById("reopenFinale").addEventListener("click",()=>{finaleDismissed=false;showFinale(true)});
start();
