const db=createDb();let doneIds=new Set(),sessionId=getActiveSession()||randomSession(),finale=false;
const WALKER_POINTS=[[137,490],[184,433],[392,222],[540,94],[646,309],[552,405]];
setActiveSession(sessionId);document.getElementById("sessionLabel").textContent=sessionId;
function celebrate(sector){const burst=document.getElementById("unlockBurst"),map=document.querySelector(".map-card");burst.innerHTML=`<i>✦</i><i>•</i><b>PLING!</b><span>${sector.name} ist freigeschaltet.</span><i>✦</i><i>•</i>`;burst.classList.remove("hidden");map.classList.add("map-celebrate");setTimeout(()=>{burst.classList.add("hidden");map.classList.remove("map-celebrate")},1800)}
function showFinale(){document.getElementById("boardFinale").classList.remove("hidden")}
function renderBoard(){document.querySelectorAll("[data-sector]").forEach(node=>node.classList.toggle("done",doneIds.has(node.dataset.sector)));const reached=SECTORS.filter(sector=>doneIds.has(sector.id)).length,point=WALKER_POINTS[Math.min(reached,WALKER_POINTS.length-1)];document.getElementById("jesusWalker").setAttribute("transform",`translate(${point[0]} ${point[1]})`);document.getElementById("expeditionRoute").style.strokeDashoffset=100-reached/SECTORS.length*100;document.getElementById("doneCount").textContent=doneIds.size;document.getElementById("progressBar").style.width=`${doneIds.size/SECTORS.length*100}%`;document.getElementById("sectorList").innerHTML=SECTORS.map(s=>`<div class="${doneIds.has(s.id)?"done":""}"><img src="${s.art}" alt=""><span>${doneIds.has(s.id)?"✓":"○"}</span><small><b>${s.name}</b>${s.title}</small></div>`).join("");if(doneIds.size===SECTORS.length||finale)showFinale()}
function acceptRow(row){if(row.session_id!==sessionId||row.status!=="erledigt")return;if(row.sektor==="finale"){finale=true;showFinale();return}const sector=SECTORS.find(s=>s.id===row.sektor);if(!sector||doneIds.has(row.sektor))return;doneIds.add(row.sektor);renderBoard();celebrate(sector)}
async function refresh(){const rows=await readProgress(db,sessionId);doneIds=completedSectorIds(rows);finale=finaleRequested(rows);renderBoard()}
async function start(){try{await refresh();if(!db){setConnectionStatus("Demo-Modus",false);window.addEventListener("storage",event=>{if(event.key===LOCAL_KEY)refresh()});window.addEventListener("berg-local-progress",event=>acceptRow(event.detail));return}setConnectionStatus("Live verbunden",true);db.channel(`tafel-${sessionId}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"fortschritt",filter:`session_id=eq.${sessionId}`},payload=>acceptRow(payload.new)).subscribe()}catch(error){console.error(error);setConnectionStatus("Verbindung prüfen",false)}}
document.getElementById("closeFinale").addEventListener("click",()=>document.getElementById("boardFinale").classList.add("hidden"));start();
