const db=createDb();let rows=[],doneIds=new Set(),completion=new Map(),sessionId=getActiveSession()||randomSession(),finale=false,locked=false,groupTarget=1,refreshing=false;
const AVATAR_POINTS=[[10,88],[28,72],[60,37],[81,58],[63,80]];
setActiveSession(sessionId);document.getElementById("sessionLabel").textContent=sessionId;
function celebrate(sector){const burst=document.getElementById("unlockBurst"),map=document.querySelector(".map-card");burst.innerHTML=`<i>✦</i><i>•</i><b>PLING!</b><span>${sector.name} ist freigeschaltet.</span><i>✦</i><i>•</i>`;burst.classList.remove("hidden");map.classList.add("map-celebrate");setTimeout(()=>{burst.classList.add("hidden");map.classList.remove("map-celebrate")},1800)}
function showFinale(){document.getElementById("boardFinale").classList.remove("hidden")}
function groupProgressMap(){const groups=new Map(),excluded=excludedGroups(rows);groupAvatarsFromRows(rows).forEach((avatar,group)=>groups.set(group,new Set()));rows.filter(row=>row.status==="erledigt"&&row.sektor!=="control"&&row.sektor!=="finale"&&row.gruppen_id!=="lehrkraft"&&!excluded.has(row.gruppen_id)).forEach(row=>{if(!groups.has(row.gruppen_id))groups.set(row.gruppen_id,new Set());groups.get(row.gruppen_id).add(row.sektor)});return groups}
function renderGroupAvatars(){const layer=document.getElementById("groupAvatarLayer"),avatars=groupAvatarsFromRows(rows),groups=[...groupProgressMap()].sort(([a],[b])=>a.localeCompare(b));layer.innerHTML=groups.map(([group,sectors],index)=>{const furthest=SECTORS.reduce((highest,sector,sectorIndex)=>sectors.has(sector.id)?sectorIndex:highest,-1)+1,point=AVATAR_POINTS[Math.min(furthest,AVATAR_POINTS.length-1)],avatar=avatarById(avatars.get(group)),offset=(index%5-2)*1.4;return `<div class="group-map-avatar" style="--x:${point[0]+offset}%;--y:${point[1]+Math.floor(index/5)*3}%;--avatar-pos:${avatar.pos}" title="${escapeHtml(group)}"><span class="avatar-token"></span><b>${escapeHtml(group)}</b></div>`}).join("")}
function renderAvatarProgress(){const list=document.getElementById("avatarProgressList"),avatars=groupAvatarsFromRows(rows),groups=[...groupProgressMap()].sort(([a],[b])=>a.localeCompare(b));list.innerHTML=groups.length?groups.map(([group,sectors])=>{const count=SECTORS.filter(sector=>sectors.has(sector.id)).length,current=SECTORS[Math.min(count,SECTORS.length-1)],avatar=avatarById(avatars.get(group));return `<div class="avatar-progress-card"><span class="avatar-token tiny" style="--avatar-pos:${avatar.pos}"></span><small><b>${escapeHtml(group)}</b><span>${count}/${SECTORS.length} · ${count===SECTORS.length?"bereit fürs Finale":current.name}</span></small><i style="width:${count/SECTORS.length*100}%"></i></div>`}).join(""):"<p class='privacy-note'>Noch keine Gruppenavatare gewählt.</p>"}
function renderClassCompass(){
  const target=document.getElementById("classCompass");
  if(!target)return;
  const totals=classValueTotals(rows),max=Math.max(1,...VALUE_KEYS.map(key=>totals[key]));
  target.innerHTML=`<div class="class-compass">${VALUE_KEYS.map(key=>`<div class="compass-row"><b>${VALUE_LABELS[key]}</b><span>${totals[key]}</span><i><em style="width:${totals[key]/max*100}%"></em></i></div>`).join("")}</div><p class="privacy-note">Aus anonymen Spielentscheidungen aktiver Gruppen berechnet.</p>`;
}
function renderCardWall(){
  const target=document.getElementById("cardWall");
  if(!target)return;
  const cards=cardRows(rows),unique=[...new Map(cards.map(card=>[`${card.type}:${card.name}`,card])).values()];
  target.innerHTML=unique.length?`<div class="card-wall">${unique.slice(-18).map(card=>`<span><b>${escapeHtml(card.name)}</b><small>${escapeHtml(card.type)}</small></span>`).join("")}</div>`:"<p class='privacy-note'>Noch keine Sammelkarten freigeschaltet.</p>";
}
function renderPlenumArena(){
  const target=document.getElementById("plenumArena");
  if(!target)return;
  const products=productRows(rows).slice(-5).reverse(),diagnostics=diagnosticSummary(rows).slice(0,3),debates=debateRows(rows);
  const debateColumns=DEBATE_FINALE.positions.map((position,index)=>{
    const items=debates.filter(item=>item.side===index).slice(-5).reverse();
    return `<div><h3>Position ${index+1}</h3><p>${escapeHtml(position)}</p>${items.length?items.map(item=>`<span class="argument-pill">${escapeHtml(item.text)}</span>`).join(""):"<small>Noch keine Argumentkarten.</small>"}</div>`;
  }).join("");
  target.innerHTML=`<p class="final-question compact">${escapeHtml(DEBATE_FINALE.question)}</p><div class="plenum-columns">${debateColumns}</div><h3>Merksätze</h3><div class="product-ticker">${products.length?products.map(item=>`<span>${escapeHtml(item.text)}</span>`).join(""):"<small>Noch keine Merksätze eingegangen.</small>"}</div><h3>Gemeinsam genauer hinschauen</h3><div class="diagnostic-ticker">${diagnostics.length?diagnostics.map(item=>{const sector=SECTORS.find(s=>s.id===item.sector);return`<span>${escapeHtml(sector?.name||item.sector)}: ${item.count} Stolperstellen</span>`}).join(""):"<small>Keine auffälligen Stolperstellen.</small>"}</div>`;
}
function renderBoard(){document.querySelectorAll("[data-sector]").forEach(node=>node.classList.toggle("done",doneIds.has(node.dataset.sector)));document.getElementById("boardLock").classList.toggle("hidden",!locked);document.getElementById("groupTargetLabel").textContent=`${WORK_MODES[activeWorkMode(rows)].name} · ${groupTarget} ${groupTarget===1?"Gruppe":"Gruppen"}`;const reached=SECTORS.filter(sector=>doneIds.has(sector.id)).length;document.getElementById("expeditionRoute").style.strokeDashoffset=100-reached/SECTORS.length*100;document.getElementById("doneCount").textContent=reached;document.getElementById("progressBar").style.width=`${reached/SECTORS.length*100}%`;document.getElementById("sectorList").innerHTML=SECTORS.map(s=>{const state=completion.get(s.id)||{count:0,required:1,complete:false};return `<div class="${state.complete?"done":""}"><img src="${s.art}" alt=""><span>${state.complete?"✓":state.count}</span><small><b>${s.name}</b>${state.complete?s.title:`${state.count} / ${state.required} Gruppenbeiträge`}</small></div>`}).join("");renderGroupAvatars();renderAvatarProgress();renderClassCompass();renderCardWall();renderPlenumArena();if(reached===SECTORS.length||finale)showFinale()}
async function acceptRow(row){if(row.session_id!==sessionId||row.status!=="erledigt")return;if(row.sektor==="finale"){finale=true;showFinale();return}const before=new Set(doneIds);await refresh();const sector=SECTORS.find(s=>s.id===row.sektor);if(sector&&!before.has(sector.id)&&doneIds.has(sector.id))celebrate(sector)}
async function refresh(){if(refreshing)return;refreshing=true;try{rows=await readProgress(db,sessionId);completion=sectorCompletion(rows);doneIds=completedSectorIds(rows);finale=finaleRequested(rows);locked=isSessionLocked(rows);groupTarget=effectiveGroupTargetFromRows(rows);renderBoard()}finally{refreshing=false}}
async function start(){try{await refresh();setInterval(refresh,3000);document.addEventListener("visibilitychange",()=>{if(!document.hidden)refresh()});if(!db){setConnectionStatus("Demo-Modus",false);window.addEventListener("storage",event=>{if(event.key===LOCAL_KEY)refresh()});window.addEventListener("berg-local-progress",event=>acceptRow(event.detail));return}setConnectionStatus("Live verbunden",true);db.channel(`tafel-${sessionId}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"fortschritt",filter:`session_id=eq.${sessionId}`},payload=>acceptRow(payload.new)).subscribe(status=>{if(status==="SUBSCRIBED")setConnectionStatus("Live verbunden",true)})}catch(error){console.error(error);setConnectionStatus("Verbindung prüfen",false)}}
document.getElementById("fullscreenMap").addEventListener("click",async()=>{const map=document.querySelector(".map-card");try{if(document.fullscreenElement){await document.exitFullscreen();document.getElementById("fullscreenMap").textContent="Karte Vollbild"}else{await map.requestFullscreen();document.getElementById("fullscreenMap").textContent="Vollbild verlassen"}}catch{map.classList.toggle("map-fullscreen-fallback")}});
document.addEventListener("fullscreenchange",()=>document.getElementById("fullscreenMap").textContent=document.fullscreenElement?"Vollbild verlassen":"Karte Vollbild");
document.getElementById("closeFinale").addEventListener("click",()=>document.getElementById("boardFinale").classList.add("hidden"));start();
