'use strict';
const $=s=>document.querySelector(s),app=$('#app'),key='ares-berufsorientierung-v2',limit=2400;
const fresh=()=>({version:2,started:false,stage:0,elapsed:0,timed:false,paused:false,complete:false,solved:false,hints:chapters.map(()=>0),mistakes:0,values:{matches:[],choice:'',checks:[],order:['erproben','reflektieren','kontakt','fragen'],code:''},reflection:{strength:'',field:'',question:'',step:'',support:'',when:''}});
let state=fresh(),feedback='',storageOK=true,lastTick=Date.now();
try{const s=JSON.parse(localStorage.getItem(key));if(s?.version===2&&Number.isInteger(s.stage)&&s.stage>=0&&s.stage<chapters.length&&Array.isArray(s.hints)&&s.hints.length===chapters.length&&s.values&&s.reflection&&Number.isFinite(s.elapsed))state={...fresh(),...s,paused:s.started&&!s.complete};}catch{storageOK=false;}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>`${String(Math.floor(n/60)).padStart(2,'0')}:${String(Math.floor(n%60)).padStart(2,'0')}`;
function save(){try{localStorage.setItem(key,JSON.stringify(state));}catch{storageOK=false;}}
function header(){let count=state.complete?6:state.stage+Number(state.solved);return `<header class="top"><div class="brand">ARES<span> /</span></div><div class="top-right"><a href="lehrkraft.html" target="_blank" rel="noopener">Für Lehrkräfte</a>${state.started?`<span class="mono" id="clock" aria-label="${state.timed?'Verbleibende Zeit':'Spielzeit'}">${fmt(state.timed?Math.max(0,limit-state.elapsed):state.elapsed)}</span>${!state.complete?'<button data-action="pause">Pause</button>':''}`:'<span class="tag mono">MISSION BERUFSZUKUNFT</span>'}</div></header>${state.started?`<div class="progress" role="progressbar" aria-label="Geöffnete Bereiche" aria-valuemin="0" aria-valuemax="6" aria-valuenow="${count}"><div style="width:${count/6*100}%"></div></div>`:''}`;}
function intro(){return `<main class="intro"><section><p class="eyebrow">Escape Room zur Beruflichen Orientierung</p><h1>MISSION<br>BERUFSZUKUNFT<span style="color:var(--orange)">.</span></h1><p class="lead">Sechs verschlossene Bereiche. Eine beschädigte Crewakte. Und viele Wege in die Zukunft.</p><p class="muted">Begleitet Noa auf einer Marsstation. Rekonstruiert Stärken, entschlüsselt Berufsfelder und wertet Praxiserfahrungen aus. Mit jedem gelösten Rätsel öffnet ihr einen Bereich – bis das Rettungssignal gesendet werden kann.</p><div class="mission-meta"><div><strong>2–4 Personen</strong>auch allein spielbar</div><div><strong>6 Kapitel</strong>plus persönliche Reflexion</div><div><strong>Klasse 9/10+</strong>Brücke zur Sek II</div></div><div class="settings"><label for="mode">Spielmodus</label><select id="mode"><option value="free">Ohne Zeitdruck</option><option value="timed">40 Minuten · pausierbar</option></select></div><button class="primary" data-action="start">Crewakte öffnen →</button><p class="small muted" style="margin-top:18px">Kein Berufstest. Keine Rangliste. Eure eigenen Interessen werden nicht bewertet.</p><details><summary>So spielt ihr zusammen</summary><p class="small muted">Lest die Dokumente, besprecht eure Begründung und bedient das Terminal gemeinsam. Wechselt nach jedem Kapitel die Rollen. Nach jeder Tür folgt eine Gesprächsfrage für euch. Tipps gibt es in drei Stufen ohne Abzug. Ton ist nicht erforderlich. Euer Fortschritt bleibt nur in diesem Browser.</p></details></section><aside class="visual"><img src="station.png" alt="Eine Forschungsstation in einer felsigen Marslandschaft vor einem Staubsturm"><div class="visual-caption"><span class="eyebrow">ARES / Crewarchiv gesperrt</span><strong>Die Zukunft hat mehr als einen Weg.</strong><span class="mono muted">SOL 218 / MISSION BERUFSZUKUNFT</span></div></aside></main>`;}
function panel(label,body){return `<section class="panel"><div class="panel-label">${label}</div>${body}</section>`;}
function fragments(){let n=state.stage+Number(state.solved);return chapters.slice(0,Math.min(5,n)).map(c=>`<div class="row"><span>${c.fragment[0]}</span><strong class="mono">${c.fragment[1]}</strong></div>`).join('')||'<p>Noch keine Fragmente.</p>';}
function sidebar(){return `<aside class="sidebar"><p class="eyebrow">Euer Weg durch die Station</p><nav class="stations" aria-label="Kapitel">${chapters.map((c,i)=>`<div class="station ${i<state.stage||i===state.stage&&state.solved?'done':i===state.stage?'current':''}" ${i===state.stage?'aria-current="step"':''}><span class="num">${i<state.stage?'✓':i+1}</span><span class="name">${c.name}</span></div>`).join('')}</nav><div class="sidebar-bottom"><p>Öffnet den nächsten Bereich mit eurer begründeten Lösung.</p><details><summary>Missionsjournal</summary>${fragments()}</details><p>${storageOK?'Fortschritt nur in diesem Browser gespeichert.':'Speichern ist nicht verfügbar. Lasst die Seite geöffnet.'}</p></div></aside>`;}
function options(c,index){return `<option value="">Bitte zuordnen</option>${c.options.map(([id,label])=>`<option value="${id}" ${state.values.matches[index]===id?'selected':''}>${label}</option>`).join('')}`;}
function answerUI(c){let v=state.values;if(c.type==='match')return c.prompts.map((p,i)=>`<div class="control"><label for="match-${i}">${p}</label><select class="answer-select" id="match-${i}" data-match="${i}">${options(c,i)}</select></div>`).join('');
if(c.type==='single'||c.type==='evidence')return `<fieldset class="choices"><legend>${c.prompts[0]}</legend>${c.options.map(([id,label])=>`<label class="choice"><input type="radio" name="choice" value="${id}" ${v.choice===id?'checked':''}><span>${label}</span></label>`).join('')}</fieldset>${c.type==='evidence'?`<fieldset class="choices"><legend>Welche zwei Belege stützen die Aussage?</legend>${c.checks.map(([id,label])=>`<label class="choice"><input type="checkbox" name="evidence" value="${id}" ${v.checks.includes(id)?'checked':''}><span>${label}</span></label>`).join('')}</fieldset>`:''}`;
return `<p class="muted">Verschiebt die Schritte mit den Pfeilen. Oben beginnt der Plan.</p><ol class="order-list">${v.order.map((id,i)=>`<li><b class="mono">${i+1}</b><span>${c.steps[id]}</span><button type="button" data-move="${i}" data-dir="-1" aria-label="${c.steps[id]} nach oben" ${i===0?'disabled':''}>↑</button><button type="button" data-move="${i}" data-dir="1" aria-label="${c.steps[id]} nach unten" ${i===3?'disabled':''}>↓</button></li>`).join('')}</ol><details open><summary>Missionsjournal: fünf Fragmente</summary>${fragments()}</details><label for="rescue-code">Fünfstellige Kennung aus dem Funkprotokoll</label><input class="code" id="rescue-code" inputmode="numeric" maxlength="12" autocomplete="off" value="${esc(v.code)}" placeholder="·····">`;}
function game(){let c=chapters[state.stage];return `<div class="shell">${sidebar()}<main class="workspace"><div class="stage-head"><div><span class="eyebrow">Kapitel ${state.stage+1} / 06 · ${c.door}</span><h2 tabindex="-1" id="stage-title">${c.name}</h2></div><span class="tag mono">${state.solved?'BEREICH GEÖFFNET':'ZUGANG GESPERRT'}</span></div><div class="log"><strong>JUNO / MISSIONSBEGLEITUNG</strong>${c.log}</div>${state.solved?`<section class="panel success"><p class="eyebrow">${c.door} geöffnet</p><h3>${c.win}</h3><p>Fragment gesichert: <b class="mono">${c.fragment.join(' / ')}</b></p><div class="transfer"><p class="eyebrow">Und was hat das mit euch zu tun?</p><p>${c.transfer}</p><p class="small muted">Besprecht die Frage kurz. Es gibt keine Musterantwort und keinen Bewertungsmaßstab für eure persönlichen Interessen.</p></div><button class="primary" data-action="next">Weiter: ${chapters[state.stage+1].name} →</button></section>`:`<form id="puzzle-form"><div class="puzzle-grid">${panel('01 / Dokumente',`<h3>${c.title}</h3><p>${c.intro}</p>${c.evidence.map(([label,text])=>`<article class="evidence-note"><h4>${label}</h4><p>${text}</p></article>`).join('')}`)}${panel('02 / Zugangsterminal',answerUI(c))}</div><div class="actions"><button class="primary" type="submit">${state.stage===5?'Plan und Rettungssignal prüfen':'Lösung prüfen'}</button><button type="button" data-action="hint" ${state.hints[state.stage]===3?'disabled':''}>${state.hints[state.stage]?`Nächster Tipp (${state.hints[state.stage]}/3)`:'Tipp anfordern'}</button></div><div class="feedback" role="status" aria-live="polite">${esc(feedback)}</div>${state.hints[state.stage]?`<aside class="hint"><span class="eyebrow">Tipp ${state.hints[state.stage]} / 3</span><p>${c.hints[state.hints[state.stage]-1]}</p></aside>`:''}</form>`}</main></div>`;}
const reflectionLabels={strength:'Eine Stärke und ein Beispiel aus meinem Alltag',field:'Ein Berufsfeld oder eine Tätigkeit, die ich erkunden möchte',question:'Meine noch offene Frage',step:'Mein konkreter nächster Schritt',support:'Wer oder welche Stelle kann mich unterstützen?',when:'Bis wann möchte ich den Schritt angehen?'};
function ending(){return `<main class="end"><p class="eyebrow">Mission abgeschlossen / 6 von 6 Bereichen</p><h1>NOA IST BEREIT.<br>UND IHR?</h1><div class="log"><strong>RETTUNGSTEAM / VERBINDUNG BESTÄTIGT</strong>„Crewakte rekonstruiert. Alle Bereiche offen. Wir holen euch ab.“ Noa kennt jetzt mehr Möglichkeiten und weiß, welche Fragen noch offen sind. Eine endgültige Berufswahl musste dafür niemand treffen.</div><div class="meters"><div class="meter"><span>Aktive Spielzeit</span><strong>${fmt(state.elapsed)}</strong></div><div class="meter"><span>Genutzte Tipps</span><strong>${state.hints.reduce((a,b)=>a+b,0)}</strong></div><div class="meter"><span>Bereiche geöffnet</span><strong>6 / 6</strong></div></div><section class="panel"><p class="eyebrow">Transfer in euren Alltag</p><h2>Mein nächster Schritt</h2><p>Jetzt arbeitet jede Person für sich. Notiert eure Gedanken auf Papier oder füllt diesen Bogen aus. Auf einem gemeinsamen Gerät seht ihr gegenseitig die Einträge. Alles ist freiwillig; ohne Namen ausfüllen genügt.</p><p class="small muted">Die Einträge bleiben in diesem Browser und können als Textdatei gespeichert werden. Der Bogen ist eine eigene Reflexionshilfe für euer Portfolio, keine offizielle Anschlussvereinbarung.</p>${Object.entries(reflectionLabels).map(([id,label])=>`<div class="control"><label for="reflection-${id}">${label}</label><textarea id="reflection-${id}" data-reflection="${id}" rows="2" maxlength="1200">${esc(state.reflection[id])}</textarea></div>`).join('')}<div class="actions"><button class="primary" data-action="download">Meinen Bogen herunterladen</button><button data-action="blank">Leeren Bogen herunterladen</button><button data-action="clear-reflection">Einträge für nächste Person leeren</button></div><div id="reflection-status" role="status"></div></section><details><summary>Was steckt hinter den sechs Kapiteln?</summary>${chapters.map(c=>`<h3 style="margin-top:20px">${c.name}</h3><p>${c.takeaway}</p>`).join('')}</details><div class="debrief">${panel('Unterstützung finden','<p>Fragt eure Lehrkraft oder die StuBo-Koordination nach passenden Praxisangeboten. Die Berufsberatung unterstützt bei Ausbildungs- und Berufswahlfragen; bei Studienfragen hilft auch die Zentrale Studienberatung einer Hochschule.</p>')}${panel('Weiterarbeiten','<p>Nehmt eine offene Frage und einen nächsten Schritt mit in ein Beratungsgespräch oder euer persönliches Portfolio. Ausbildungs- und Studienangebote haben unterschiedliche Voraussetzungen: Prüft konkrete Angebote gemeinsam mit einer beratenden Person.</p>')}</div><button data-action="restart">Neue Mission beginnen</button></main>`;}
function pauseOverlay(){return state.paused&&state.started&&!state.complete?`<div class="overlay" role="dialog" aria-modal="true" aria-labelledby="pause-title"><section class="panel"><p class="eyebrow">Mission pausiert</p><h2 id="pause-title">Zeit zum Nachdenken.</h2><p>${state.timed&&state.elapsed>=limit?'Das Zeitfenster ist vorbei. Ihr könnt ohne Zeitdruck weiterarbeiten. Eure Ergebnisse bleiben erhalten.':'Die Uhr steht. Eure Ergebnisse bleiben erhalten.'}</p><button class="primary" data-action="resume">${state.timed&&state.elapsed>=limit?'Ohne Zeitdruck fortsetzen':'Mission fortsetzen'}</button></section></div>`:'';}
function render(focus=false){app.innerHTML=header()+(state.complete?ending():state.started?game():intro())+'<footer class="footer">ARES / Mission Berufszukunft · Eigenständiges Lernspiel zur Beruflichen Orientierung. Kein Angebot des MSB NRW. <a href="lehrkraft.html" target="_blank" rel="noopener">Didaktik und Quellen</a></footer>'+pauseOverlay();if(state.paused){$('.shell')?.setAttribute('inert','');$('.top')?.setAttribute('inert','');$('[data-action="resume"]')?.focus();}else if(focus)$('#stage-title')?.focus();}
function validate(){let c=chapters[state.stage],v=state.values;if(c.type==='match')return c.answer.every((a,i)=>v.matches[i]===a)&&v.matches.length===c.answer.length;if(c.type==='single')return v.choice===c.answer;if(c.type==='evidence')return v.choice===c.answer&&v.checks.length===2&&c.checkAnswer.every(a=>v.checks.includes(a));return v.order.join(',')===c.answer.join(',')&&v.code.replace(/\s/g,'')===c.code;}
function submit(){if(!state.started||state.paused||state.solved||state.complete)return false;let c=chapters[state.stage];if(validate()){if(state.stage===5)state.complete=true;else state.solved=true;feedback='';save();render(true);return true;}state.mistakes++;feedback=c.type==='evidence'?'Prüft die Schlussfolgerung und genau zwei Belege. Die Notizen stützen keine endgültige Festlegung.':c.type==='order'?'Prüft sowohl die Reihenfolge des Plans als auch die fünf Fragmente im Funkprotokoll.':'Die Lösung passt noch nicht zu allen Dokumenten. Vergleicht jede Auswahl mit der beschriebenen Tätigkeit oder Frage.';save();$('.feedback').textContent=feedback;return false;}
function download(blank=false){let text='ARES – Mein nächster Schritt\nPersönliche Reflexion zur Beruflichen Orientierung\n\n'+Object.entries(reflectionLabels).map(([id,label])=>label+'\n'+(blank?'________________________________________':state.reflection[id]||'(noch offen)')).join('\n\n')+'\n\nEigene Reflexionshilfe; keine offizielle Anschlussvereinbarung.\n';let url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=blank?'ARES-Reflexionsbogen-leer.txt':'ARES-mein-naechster-Schritt.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('#reflection-status').textContent='Der Download wurde gestartet.';}
app.addEventListener('submit',e=>{e.preventDefault();submit();});
app.addEventListener('input',e=>{const t=e.target;if(t.dataset.match!==undefined)state.values.matches[Number(t.dataset.match)]=t.value;if(t.name==='choice')state.values.choice=t.value;if(t.name==='evidence'){state.values.checks=state.values.checks.filter(x=>x!==t.value);if(t.checked)state.values.checks.push(t.value);}if(t.id==='rescue-code')state.values.code=t.value;if(t.dataset.reflection)state.reflection[t.dataset.reflection]=t.value;save();});
function next(){if(!state.solved||state.stage>=5)return;state.stage++;state.solved=false;state.values=fresh().values;feedback='';save();render(true);}
app.addEventListener('click',e=>{let b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.move!==undefined){let i=Number(b.dataset.move),j=i+Number(b.dataset.dir);[state.values.order[i],state.values.order[j]]=[state.values.order[j],state.values.order[i]];save();render();document.querySelector(`[data-move="${j}"][data-dir="${b.dataset.dir}"]`)?.focus();return;}let a=b.dataset.action;if(!a)return;if(a==='download'||a==='blank'){download(a==='blank');return;}if(a==='clear-reflection'){state.reflection=fresh().reflection;save();render();$('#reflection-status').textContent='Die Einträge wurden auf diesem Gerät geleert.';return;}if(a==='next'){next();return;}if(a==='start'){state=fresh();state.started=true;state.timed=$('#mode').value==='timed';lastTick=Date.now();}if(a==='pause')state.paused=true;if(a==='resume'){if(state.timed&&state.elapsed>=limit)state.timed=false;state.paused=false;lastTick=Date.now();}if(a==='hint')state.hints[state.stage]=Math.min(3,state.hints[state.stage]+1);if(a==='restart'){state=fresh();feedback='';}save();render(a==='start');});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&state.started&&!state.complete&&!state.paused){state.paused=true;save();render();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.started&&!state.complete&&!state.paused){state.paused=true;save();render();}});
setInterval(()=>{let now=Date.now(),delta=Math.min(5,(now-lastTick)/1000);lastTick=now;if(!state.started||state.paused||state.complete)return;state.elapsed+=delta;if(state.timed&&state.elapsed>=limit){state.elapsed=limit;state.paused=true;render();}else if($('#clock'))$('#clock').textContent=fmt(state.timed?Math.max(0,limit-state.elapsed):state.elapsed);save();},1000);
render();
const modelContext=document.modelContext;
if(modelContext?.registerTool){const life=new AbortController();const register=t=>{try{Promise.resolve(modelContext.registerTool(t,{signal:life.signal})).catch(()=>{});}catch{}};
register({name:'read_mission',description:'Read educational mission progress and already requested hint. Does not include personal reflection entries or unrevealed answers.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({started:state.started,chapter:state.stage+1,title:chapters[state.stage].name,paused:state.paused,solved:state.solved,complete:state.complete,hint:state.hints[state.stage]?chapters[state.stage].hints[state.hints[state.stage]-1]:null})});
register({name:'submit_puzzle_answer',description:'Submit an answer to the active fictional case. JSON string: matches is an ordered ID array, choice is an option ID, checks is an evidence ID array; final chapter uses order array and code string. Uses the same validation as the visible terminal. Does not evaluate personal interests.',inputSchema:{type:'object',properties:{answer:{type:'string'}},required:['answer'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||typeof input.answer!=='string')throw Error('Expected JSON string.');if(!state.started||state.paused||state.solved||state.complete)throw Error('No active unsolved chapter.');let a=JSON.parse(input.answer),c=chapters[state.stage],v={...state.values};if(!a||typeof a!=='object'||Array.isArray(a))throw Error('Expected object.');if(c.type==='match'){if(!Array.isArray(a.matches)||a.matches.length!==c.prompts.length||!a.matches.every(x=>c.options.some(([id])=>id===x)))throw Error('Invalid matches.');v.matches=a.matches;}else if(c.type==='single'||c.type==='evidence'){if(!c.options.some(([id])=>id===a.choice))throw Error('Invalid choice.');v.choice=a.choice;if(c.type==='evidence'){if(!Array.isArray(a.checks)||new Set(a.checks).size!==a.checks.length||!a.checks.every(x=>c.checks.some(([id])=>id===x)))throw Error('Invalid evidence.');v.checks=a.checks;}}else{if(!Array.isArray(a.order)||a.order.length!==4||new Set(a.order).size!==4||!a.order.every(x=>Object.hasOwn(c.steps,x))||typeof a.code!=='string'||a.code.length>12)throw Error('Invalid plan.');v.order=a.order;v.code=a.code;}state.values=v;render();let accepted=submit();return {accepted,complete:state.complete,feedback:accepted?'Chapter unlocked':feedback};}});
window.addEventListener('pagehide',()=>life.abort(),{once:true});}
