'use strict';
const AresInventory = (() => {
 const colors={orange:{name:'Kupfer',hex:0xf69e67},mint:{name:'Salbei',hex:0x75c9b7},blue:{name:'Blau',hex:0x72abe8},violet:{name:'Violett',hex:0xb09bdb}};
 const tools={scanner:{name:'Datenscanner',kind:'Werkzeug',description:'Markiert eine Suchrichtung im aktuellen Raum. Wähle zuerst ein gesammeltes Dokument.'},module:{name:'Analysemodul',kind:'Werkzeug',description:'Vergleicht zwei Dokumente nebeneinander. Auch mit dem Datenscanner kombinierbar.'},lens:{name:'Fokuslinse',kind:'Kombiniertes Werkzeug',description:'Stellt zu einem Dokument eine weiterführende Frage. Liefert keine fertige Lösung.'}};
 const fresh=()=>({avatar:{name:'Crew 07',color:'orange'},view:'world',items:['scanner'],selection:[],uses:{},position:{x:0,z:2.5},listMode:false});
 const documentId=(stage,index)=>`doc-${stage}-${index}`;
 function describe(id){if(tools[id])return {id,...tools[id]};const m=/^doc-(\d)-(\d)$/.exec(id);if(m){const stage=Number(m[1]),index=Number(m[2]),c=chapters[stage],e=c?.evidence[index];if(e)return{id,name:e[0],kind:'Dokument',description:e[1],stage,index};}const f=/^fragment-(\d)$/.exec(id);if(f){const stage=Number(f[1]),fragment=chapters[stage]?.fragment;if(fragment)return{id,name:fragment[0],kind:'Fragment',description:`Kennungsfragment: ${fragment[1]}`,value:fragment[1],stage};}return null;}
 function normalize(s){const old=s.expedition;const e=fresh();if(old&&typeof old==='object'){e.avatar.name=typeof old.avatar?.name==='string'?old.avatar.name.slice(0,18):e.avatar.name;e.avatar.color=Object.hasOwn(colors,old.avatar?.color)?old.avatar.color:'orange';e.items=Array.isArray(old.items)?[...new Set(old.items.filter(id=>typeof id==='string'&&describe(id)))]:['scanner'];if(!e.items.includes('scanner'))e.items.unshift('scanner');e.selection=Array.isArray(old.selection)?old.selection.filter(id=>e.items.includes(id)&&describe(id)?.kind==='Dokument').slice(0,2):[];e.uses=old.uses&&typeof old.uses==='object'&&!Array.isArray(old.uses)?old.uses:{};e.view=old.view==='terminal'?'terminal':'world';e.listMode=old.listMode===true;if(Number.isFinite(old.position?.x)&&Number.isFinite(old.position?.z))e.position={x:Math.max(-5.5,Math.min(75.5,old.position.x)),z:Math.max(-3.5,Math.min(3.5,old.position.z))};}
 // Old saved games retain already read documents and all earlier achievements.
 for(let stage=0;stage<s.stage+(s.solved?1:0);stage++){chapters[stage].evidence.forEach((_,i)=>e.items.push(documentId(stage,i)));if(chapters[stage].fragment)e.items.push(`fragment-${stage}`);}
 if(!old){for(const i of s.values.inspected||[]){if(chapters[s.stage].evidence[i])e.items.push(documentId(s.stage,i));}e.position.x=s.stage*14;}
 e.items=[...new Set(e.items)];s.expedition=e;return e;
 }
 function itemsInRoom(stage){return chapters[stage].evidence.map(([name],i)=>({id:documentId(stage,i),name,kind:'Dokument',stage,index:i})).concat(stage===0?[{id:'module',name:'Analysemodul',kind:'Werkzeug',stage:0,index:4}]:[]);}
 function collect(s,id){const item=describe(id);if(!item||item.kind==='Fragment'||id==='scanner'||id==='lens')throw Error('Dieser Gegenstand kann hier nicht aufgenommen werden.');const room=id==='module'?0:item.stage;if(room>s.stage)throw Error('Dieser Raum ist noch verschlossen.');if(s.expedition.items.includes(id))return false;s.expedition.items.push(id);return true;}
 function select(s,id){if(!s.expedition.items.includes(id)||describe(id)?.kind!=='Dokument')throw Error('Wähle ein gesammeltes Dokument.');const a=s.expedition.selection;if(a.includes(id))a.splice(a.indexOf(id),1);else{if(a.length===2)a.shift();a.push(id);}return [...a];}
 function combine(s){if(!s.expedition.items.includes('scanner')||!s.expedition.items.includes('module'))throw Error('Datenscanner und Analysemodul müssen im Inventar sein.');if(s.expedition.items.includes('lens'))return false;s.expedition.items.push('lens');return true;}
 function use(s,tool){if(!s.expedition.items.includes(tool))throw Error('Dieses Werkzeug fehlt im Inventar.');const docs=s.expedition.selection.map(describe).filter(Boolean);if(tool==='module'){if(docs.length!==2)throw Error('Wähle genau zwei Dokumente zum Vergleichen.');return {title:'Belegvergleich',documents:docs,text:'Welche Gemeinsamkeit, welcher Unterschied oder welche offene Frage fällt euch auf? Bezieht eure Aussage auf die Dokumente.'};}if(!['scanner','lens'].includes(tool))throw Error('Unbekanntes Werkzeug.');if(!docs.length)throw Error('Wähle zuerst ein Dokument im Inventar.');const doc=docs[docs.length-1];const level=tool==='scanner'?0:2;s.expedition.uses[`${doc.stage}:${tool}`]=true;s.hints[doc.stage]=Math.max(s.hints[doc.stage],level+1);return {title:tool==='scanner'?'Scannerauswertung':'Fokusfrage',documents:[doc],text:chapters[doc.stage].hints[level]};}
 function ready(s){return chapters[s.stage].evidence.every((_,i)=>s.expedition.items.includes(documentId(s.stage,i)));}
 function award(s){const id=`fragment-${s.stage}`;if(chapters[s.stage].fragment&&!s.expedition.items.includes(id))s.expedition.items.push(id);}
 function fragmentCode(s){return [4,0,3,1,2].map(i=>s.expedition.items.includes(`fragment-${i}`)?chapters[i].fragment[1]:'').join('');}
 return {colors,tools,fresh,normalize,describe,documentId,itemsInRoom,collect,select,combine,use,ready,award,fragmentCode};
})();
