const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
let stored=null,blobSent=null,downloadName=null;
function boot(saved=null){const nodes=new Map(),handlers={},tools=[],windowHandlers={};const node=()=>({innerHTML:'',textContent:'',value:'free',addEventListener(name,fn){handlers[name]=fn},setAttribute(){},focus(){}});let now=0,tick;
const ctx={console,Date:class extends Date{static now(){return now}},JSON,Math,Number,String,Array,Set,Promise,AbortController,Blob,URL:{createObjectURL(b){blobSent=b;return 'blob:test'},revokeObjectURL(){}},setTimeout(fn){fn()},localStorage:{getItem(){return saved},setItem(k,v){stored=v}},setInterval(fn){tick=fn},window:{addEventListener(n,f){windowHandlers[n]=f}},document:{hidden:false,querySelector(s){if(!nodes.has(s))nodes.set(s,node());return nodes.get(s)},createElement(){return{click(){downloadName=this.download}}},addEventListener(n,f){handlers['document:'+n]=f},modelContext:{registerTool(t){tools.push(t)}}}};
vm.createContext(ctx);vm.runInContext(fs.readFileSync('dist/mission.js','utf8')+'\n'+fs.readFileSync('dist/game.js','utf8'),ctx);return {ctx,tools,nodes,handlers,run:s=>vm.runInContext(s,ctx),tick(seconds){now+=seconds*1000;tick()},click(action){handlers.click({target:{closest(){return{dataset:{action},disabled:false}}}})}};
}
async function main(){const b=boot();assert.equal(b.tools.length,2);const submit=b.tools.find(t=>t.name==='submit_puzzle_answer'),read=b.tools.find(t=>t.name==='read_mission');
assert.equal(read.annotations.readOnlyHint,true);assert.ok(!b.run('app.innerHTML').includes('Schlüssel 583'));
assert.throws(()=>submit.execute({answer:'{}'}));b.click('start');assert.equal(b.run('state.started'),true);assert.equal(b.run('state.timed'),false);
b.click('next');assert.equal(b.run('state.stage'),0,'Cannot skip chapter');
assert.throws(()=>submit.execute({answer:'{"matches":["unknown"]}'}));assert.equal(b.run('state.values.matches.length'),0);
assert.equal(submit.execute({answer:'{"matches":["organisieren","analysieren","kommunizieren"]}'}).accepted,false);
b.click('hint');assert.ok(b.run('app.innerHTML').includes('Achtet auf das konkrete Handeln'));assert.ok(!b.run('app.innerHTML').includes('A: Analysieren (5)'));
const cases=[{matches:['analysieren','kommunizieren','organisieren']},{matches:['technik','soziales','gestaltung','wirtschaft']},{choice:'praxis'},{choice:'offen',checks:['A','B']},{matches:['dual','schulisch','studium']},{order:['fragen','kontakt','erproben','reflektieren'],code:'6 7 2 4 9'}];
for(let i=0;i<cases.length;i++){assert.equal(b.run('state.stage'),i);if(i===3){assert.equal(submit.execute({answer:JSON.stringify({choice:'offen',checks:['A','X']})}).accepted,false);assert.equal(submit.execute({answer:JSON.stringify({choice:'offen',checks:['A']})}).accepted,false);}if(i===5){assert.equal(submit.execute({answer:JSON.stringify({...cases[i],code:'12345'})}).accepted,false);assert.equal(submit.execute({answer:JSON.stringify({...cases[i],order:['kontakt','fragen','erproben','reflektieren']})}).accepted,false);}assert.equal(submit.execute({answer:JSON.stringify(cases[i])}).accepted,true);if(i<5){assert.ok(b.run('app.innerHTML').includes('Und was hat das mit euch zu tun?'));assert.throws(()=>submit.execute({answer:JSON.stringify(cases[i])}));b.click('next');}}
assert.equal(b.run('state.complete'),true);assert.ok(b.run('app.innerHTML').includes('6 / 6'));assert.equal(b.run('state.reflection.step'),'','Personal answer not required or scored');
b.run('state.reflection.step="Praktikum & Beratung <b>";save();render()');assert.ok(b.run('app.innerHTML').includes('&lt;b&gt;'));assert.ok(!JSON.stringify(read.execute()).includes('Praktikum'));
b.click('download');assert.equal(downloadName,'ARES-mein-naechster-Schritt.txt');assert.ok((await blobSent.text()).includes('Praktikum & Beratung <b>'));
b.click('blank');assert.ok(!(await blobSent.text()).includes('Praktikum & Beratung'));
b.click('clear-reflection');assert.equal(b.run('state.reflection.step'),'');
const finished=boot(stored);assert.equal(finished.run('state.complete'),true);assert.equal(finished.run('state.paused'),false);
const paused=boot();paused.click('start');paused.tick(2);assert.equal(paused.run('state.elapsed'),2);paused.click('pause');paused.tick(2);assert.equal(paused.run('state.elapsed'),2);assert.throws(()=>paused.tools[1].execute({answer:JSON.stringify(cases[0])}));const reload=boot(stored);assert.equal(reload.run('state.paused'),true);reload.click('resume');assert.equal(reload.run('state.paused'),false);reload.run('state.timed=true;state.elapsed=2399');reload.tick(2);assert.equal(reload.run('state.paused'),true);reload.click('resume');assert.equal(reload.run('state.timed'),false);
for(const file of ['dist/index.html','dist/lehrkraft.html']){const html=fs.readFileSync(file,'utf8');for(const m of html.matchAll(/(?:src|href)="([^"#]+)"/g)){if(!/^https?:/.test(m[1]))assert.ok(fs.existsSync('dist/'+m[1]),'Missing asset '+m[1]);}}
assert.ok(!fs.readFileSync('dist/style.css','utf8').includes('fonts.googleapis.com'));
console.log('PASS: all 6 chapters, wrong/missing evidence, final sequence+code, progression guards, requested hints only, personal reflection escaping/download/clear, save+resume, timer expiry, internal assets. WebMCP contracts use a mock registry; browser compatibility not tested.');}
main().catch(e=>{console.error(e);process.exitCode=1});
